<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ArchaGearController;
use App\Http\Controllers\GuildGroupController;
use App\Http\Controllers\PlayerController;
use App\Http\Controllers\PlayerLinkController;
use App\Http\Controllers\PlayerLinkRequestController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ActivityDefinitionController;
use App\Http\Controllers\LootImportController;
use App\Http\Controllers\ActivityLootController;
use App\Http\Controllers\PrimeCalculationController;
use App\Http\Controllers\PendingEarningController;
use App\Http\Controllers\TreasuryController;
use App\Http\Controllers\AuctionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LootCatalogController;
use App\Http\Controllers\PayoutController;
use App\Http\Controllers\PayoutPreviewController;
use App\Http\Controllers\TreasuryItemSaleController;
use App\Http\Controllers\TreasuryItemIssueController;
use App\Http\Controllers\TreasuryIssueOptionsController;
use App\Http\Controllers\TreasuryTransactionController;
use App\Http\Controllers\SelfPlayerController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\RosterReadinessController;
use App\Http\Controllers\AttendanceAnalyticsController;
use App\Http\Controllers\FinancialReconciliationController;
use App\Http\Controllers\PayoutExportController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\AdminSettingsController;
use App\Http\Controllers\PartySquadController;
use App\Http\Controllers\MediaPostController;
use App\Services\DiscordProfileService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/archa-gear/items/{itemId}', [ArchaGearController::class, 'image'])
    ->whereNumber('itemId')->middleware('throttle:120,1');
Route::get('/archa-gear/assets/{type}/{assetId}', [ArchaGearController::class, 'asset'])
    ->whereIn('type', ['items', 'runes', 'gems'])->whereNumber('assetId')->middleware('throttle:120,1');

Route::middleware(['auth:sanctum', 'throttle:api'])->group(function (): void {
    Route::get('/me', fn (Request $request) => $request->user()?->load(['player', 'pendingPlayerLinkRequest.player:id,nickname,class']));
    Route::post('/me/discord-profile/sync', function (Request $request, DiscordProfileService $discord) {
        return $discord->sync($request->user())->load(['player', 'pendingPlayerLinkRequest.player:id,nickname,class']);
    })->middleware('throttle:6,1');
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/me/player', [SelfPlayerController::class, 'link']);
    Route::get('/me/player-options', [SelfPlayerController::class, 'options']);
    Route::patch('/me/player/nickname', [SelfPlayerController::class, 'rename']);
    Route::patch('/me/player/class', [SelfPlayerController::class, 'changeClass']);
    Route::patch('/me/player/profile', [SelfPlayerController::class, 'updateProfile']);
    Route::post('/me/player/archa-gear', [ArchaGearController::class, 'self'])->middleware('throttle:6,1');
    Route::post('/me/player/archa-gear-snapshot', [ArchaGearController::class, 'snapshot'])->middleware('throttle:6,1');
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications/read-all', [NotificationController::class, 'readAll']);
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'read']);

    Route::middleware('player.linked')->group(function (): void {
    Route::get('/media', [MediaPostController::class, 'index']);
    Route::post('/media/metadata', [MediaPostController::class, 'metadata'])->middleware('throttle:20,1');
    Route::post('/media', [MediaPostController::class, 'store'])->middleware('throttle:10,1');
    Route::get('/media/{mediaPost}/file', [MediaPostController::class, 'media'])->name('media.file');
    Route::post('/media/{mediaPost}/reaction', [MediaPostController::class, 'react']);
    Route::delete('/media/{mediaPost}', [MediaPostController::class, 'destroy']);
    Route::get('/admin/users', [AdminUserController::class, 'index']);
    Route::patch('/admin/users/{managedUser}/roles', [AdminUserController::class, 'updateRole']);
    Route::delete('/admin/users/{managedUser}', [AdminUserController::class, 'destroy']);
    Route::get('/admin/audit-logs', AuditLogController::class);
    Route::get('/admin/settings', AdminSettingsController::class);
    Route::patch('/admin/settings/economy', [AdminSettingsController::class, 'updateEconomy']);
    Route::get('/admin/player-link-requests', [PlayerLinkRequestController::class, 'index']);
    Route::post('/admin/player-link-requests/{playerLinkRequest}/approve', [PlayerLinkRequestController::class, 'approve']);
    Route::post('/admin/player-link-requests/{playerLinkRequest}/reject', [PlayerLinkRequestController::class, 'reject']);

    Route::delete('/players/{player}/permanent', [PlayerController::class, 'destroyPermanently']);
    Route::patch('/players/{player}/profile', [PlayerController::class, 'updateProfile']);
    Route::post('/players/{player}/archa-gear', [ArchaGearController::class, 'player'])->middleware('throttle:6,1');
    Route::get('/players/{player}/activities', [PlayerController::class, 'activities']);
    Route::get('/players/{player}/earnings', [PlayerController::class, 'earnings']);
    Route::get('/players/{player}/gear-score-history', [PlayerController::class, 'gearScoreHistory']);
    Route::apiResource('players', PlayerController::class);
    Route::post('/players/{player}/activate', [PlayerController::class, 'activate']);
    Route::put('/players/{player}/group', [PlayerController::class, 'move']);
    Route::put('/players/{player}/user', PlayerLinkController::class);
    Route::apiResource('groups', GuildGroupController::class)->except('show');
    Route::get('/groups/{group}/squads', [PartySquadController::class, 'show']);
    Route::post('/groups/{group}/squads', [PartySquadController::class, 'store']);
    Route::patch('/groups/{group}/squads/{squad}', [PartySquadController::class, 'update']);
    Route::delete('/groups/{group}/squads/{squad}', [PartySquadController::class, 'destroy']);
    Route::put('/groups/{group}/squads/{squad}/players', [PartySquadController::class, 'assign']);
    Route::delete('/groups/{group}/squads/players/{player}', [PartySquadController::class, 'unassign']);
    Route::apiResource('activity-definitions', ActivityDefinitionController::class)->except('show');
    Route::post('/activity-definitions/{activityDefinition}/icon', [ActivityDefinitionController::class, 'uploadIcon']);
    Route::delete('/activity-definitions/{activityDefinition}/icon', [ActivityDefinitionController::class, 'deleteIcon']);
    Route::apiResource('activities', ActivityController::class);
    Route::post('/activities/{activity}/players', [ActivityController::class, 'addPlayers']);
    Route::delete('/activities/{activity}/players/{playerId}', [ActivityController::class, 'removePlayer']);
    // Compatibility for records created before the mini-activity removal migration.
    Route::post('/activities/{activity}/complete', [ActivityController::class, 'complete']);
    Route::post('/activities/{activity}/reopen', [ActivityController::class, 'reopen']);
    Route::post('/activities/{activity}/loot', [ActivityLootController::class, 'store']);
    Route::patch('/activities/{activity}/loot/{loot}', [ActivityLootController::class, 'update']);
    Route::delete('/activities/{activity}/loot/{loot}', [ActivityLootController::class, 'destroy']);
    Route::post('/activities/{activity}/calculate-prime', PrimeCalculationController::class);
    Route::post('/activities/{activity}/loot-imports', [LootImportController::class, 'store']);
    Route::get('/loot-imports/{lootImport}', [LootImportController::class, 'show']);
    Route::put('/loot-imports/{lootImport}/rows/{row}', [LootImportController::class, 'updateRow']);
    Route::post('/loot-imports/{lootImport}/confirm', [LootImportController::class, 'confirm']);
    Route::get('/earnings/pending', PendingEarningController::class);
    Route::get('/payouts', [PayoutController::class, 'index']);
    Route::get('/payouts-preview', PayoutPreviewController::class);
    Route::post('/payouts', [PayoutController::class, 'store']);
    Route::get('/payouts/{payout}', [PayoutController::class, 'show']);
    Route::get('/payouts/{payout}/export', PayoutExportController::class);
    Route::delete('/payouts/{payout}', [PayoutController::class, 'destroy']);
    Route::post('/payouts/{payout}/calculate', [PayoutController::class, 'calculate']);
    Route::post('/payouts/{payout}/complete', [PayoutController::class, 'complete']);
    Route::post('/payouts/{payout}/pay-players', [PayoutController::class, 'payPlayers']);
    Route::post('/payouts/{payout}/cancel', [PayoutController::class, 'cancel']);
    Route::get('/treasury', TreasuryController::class);
    Route::get('/treasury/items', [TreasuryController::class, 'items']);
    Route::post('/treasury/transactions', [TreasuryTransactionController::class, 'store']);
    Route::get('/treasury/issue-options', TreasuryIssueOptionsController::class);
    Route::post('/treasury/items/{item}/issue', TreasuryItemIssueController::class);
    Route::post('/treasury/items/{item}/sell', TreasuryItemSaleController::class);
    Route::get('/dashboard', DashboardController::class);
    Route::get('/roster-readiness', RosterReadinessController::class);
    Route::get('/attendance-analytics', [AttendanceAnalyticsController::class, 'index']);
    Route::get('/attendance-analytics/export', [AttendanceAnalyticsController::class, 'export']);
    Route::get('/financial-reconciliation', FinancialReconciliationController::class);
    Route::get('/auctions', [AuctionController::class, 'index']);
    Route::get('/auctions/active-count', [AuctionController::class, 'activeCount']);
    Route::get('/auctions/archive', [AuctionController::class, 'archive']);
    Route::post('/auctions', [AuctionController::class, 'store']);
    Route::get('/auctions/{auction}', [AuctionController::class, 'show']);
    Route::put('/auctions/{auction}', [AuctionController::class, 'update']);
    Route::post('/auctions/{auction}/start', [AuctionController::class, 'start']);
    Route::post('/auctions/{auction}/bid', [AuctionController::class, 'bid']);
    Route::post('/auctions/{auction}/finish', [AuctionController::class, 'finish']);
    Route::post('/auctions/{auction}/cancel', [AuctionController::class, 'cancel']);
    Route::get('/loot-catalog', [LootCatalogController::class, 'index']);
    Route::post('/loot-catalog', [LootCatalogController::class, 'store']);
    Route::put('/loot-catalog/{lootCatalogItem}', [LootCatalogController::class, 'update']);
    Route::delete('/loot-catalog/{lootCatalogItem}', [LootCatalogController::class, 'destroy']);
    });
});
