<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\GuildGroupController;
use App\Http\Controllers\PlayerController;
use App\Http\Controllers\PlayerLinkController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ActivityDefinitionController;
use App\Http\Controllers\LootImportController;
use App\Http\Controllers\ActivityLootController;
use App\Http\Controllers\PrimeCalculationController;
use App\Http\Controllers\PendingEarningController;
use App\Http\Controllers\TreasuryController;
use App\Http\Controllers\AuctionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LootCatalogController;
use App\Http\Controllers\PayoutController;
use App\Http\Controllers\TreasuryItemSaleController;
use App\Http\Controllers\TreasuryItemIssueController;
use App\Http\Controllers\TreasuryIssueOptionsController;
use App\Http\Controllers\TreasuryTransactionController;
use App\Http\Controllers\SelfPlayerController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\AuditLogController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth:sanctum', 'throttle:api'])->group(function (): void {
    Route::get('/me', fn (Request $request) => $request->user()?->load('player'));
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/me/player', [SelfPlayerController::class, 'link']);
    Route::get('/me/player-options', [SelfPlayerController::class, 'options']);
    Route::patch('/me/player/nickname', [SelfPlayerController::class, 'rename']);
    Route::patch('/me/player/class', [SelfPlayerController::class, 'changeClass']);

    Route::middleware('player.linked')->group(function (): void {
    Route::get('/admin/users', [AdminUserController::class, 'index']);
    Route::patch('/admin/users/{managedUser}/roles', [AdminUserController::class, 'updateRole']);
    Route::delete('/admin/users/{managedUser}', [AdminUserController::class, 'destroy']);
    Route::get('/admin/audit-logs', AuditLogController::class);

    Route::apiResource('players', PlayerController::class);
    Route::post('/players/{player}/activate', [PlayerController::class, 'activate']);
    Route::put('/players/{player}/group', [PlayerController::class, 'move']);
    Route::put('/players/{player}/user', PlayerLinkController::class);
    Route::apiResource('groups', GuildGroupController::class)->except('show');
    Route::apiResource('activity-definitions', ActivityDefinitionController::class)->except('show');
    Route::post('/activity-definitions/{activityDefinition}/icon', [ActivityDefinitionController::class, 'uploadIcon']);
    Route::delete('/activity-definitions/{activityDefinition}/icon', [ActivityDefinitionController::class, 'deleteIcon']);
    Route::apiResource('activities', ActivityController::class);
    Route::post('/activities/{activity}/players', [ActivityController::class, 'addPlayers']);
    Route::delete('/activities/{activity}/players/{playerId}', [ActivityController::class, 'removePlayer']);
    Route::post('/activities/{activity}/complete', [ActivityController::class, 'complete']);
    Route::post('/activities/{activity}/loot', [ActivityLootController::class, 'store']);
    Route::delete('/activities/{activity}/loot/{loot}', [ActivityLootController::class, 'destroy']);
    Route::post('/activities/{activity}/calculate-prime', PrimeCalculationController::class);
    Route::post('/activities/{activity}/loot-imports', [LootImportController::class, 'store']);
    Route::get('/loot-imports/{lootImport}', [LootImportController::class, 'show']);
    Route::put('/loot-imports/{lootImport}/rows/{row}', [LootImportController::class, 'updateRow']);
    Route::post('/loot-imports/{lootImport}/confirm', [LootImportController::class, 'confirm']);
    Route::get('/earnings/pending', PendingEarningController::class);
    Route::get('/payouts', [PayoutController::class, 'index']);
    Route::post('/payouts', [PayoutController::class, 'store']);
    Route::get('/payouts/{payout}', [PayoutController::class, 'show']);
    Route::patch('/payouts/{payout}/players/{payoutPlayer}', [PayoutController::class, 'updatePlayerAmount']);
    Route::delete('/payouts/{payout}', [PayoutController::class, 'destroy']);
    Route::post('/payouts/{payout}/calculate', [PayoutController::class, 'calculate']);
    Route::post('/payouts/{payout}/complete', [PayoutController::class, 'complete']);
    Route::post('/payouts/{payout}/cancel', [PayoutController::class, 'cancel']);
    Route::get('/treasury', TreasuryController::class);
    Route::post('/treasury/transactions', [TreasuryTransactionController::class, 'store']);
    Route::get('/treasury/issue-options', TreasuryIssueOptionsController::class);
    Route::post('/treasury/items/{item}/issue', TreasuryItemIssueController::class);
    Route::post('/treasury/items/{item}/sell', TreasuryItemSaleController::class);
    Route::get('/dashboard', DashboardController::class);
    Route::get('/auctions', [AuctionController::class, 'index']);
    Route::get('/auctions/active-count', [AuctionController::class, 'activeCount']);
    Route::post('/auctions', [AuctionController::class, 'store']);
    Route::get('/auctions/{auction}', [AuctionController::class, 'show']);
    Route::put('/auctions/{auction}', [AuctionController::class, 'update']);
    Route::post('/auctions/{auction}/start', [AuctionController::class, 'start']);
    Route::post('/auctions/{auction}/bid', [AuctionController::class, 'bid']);
    Route::post('/auctions/{auction}/finish', [AuctionController::class, 'finish']);
    Route::post('/auctions/{auction}/cancel', [AuctionController::class, 'cancel']);
    Route::get('/loot-catalog', [LootCatalogController::class, 'index']);
    Route::post('/loot-catalog', [LootCatalogController::class, 'store']);
    Route::put('/loot-catalog/{lootCatalogItem}', [LootCatalogController::class, 'update']);
    Route::delete('/loot-catalog/{lootCatalogItem}', [LootCatalogController::class, 'destroy']);
    });
});
