<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
import { useActivitiesStore } from '../stores/activities.js'
import { useGuildStore } from '../stores/guild.js'
import { useConfirmationStore } from '../stores/confirmation.js'
import { useInputDialogStore } from '../stores/input-dialog.js'
import LootImportPanel from '../components/LootImportPanel.vue'
import ManualLootForm from '../components/ManualLootForm.vue'
import AppModal from '../components/AppModal.vue'
import { apiErrorMessage, useNotificationsStore } from '../stores/notifications.js'
import { formatDateTime, formatInteger, formatMoscowDateTimeInput, moscowLocalToIso } from '../utils/format.js'
const route=useRoute(); const router=useRouter(); const auth=useAuthStore(); const activities=useActivitiesStore(); const guild=useGuildStore(); const confirmStore=useConfirmationStore(); const inputDialog=useInputDialogStore(); const notifications=useNotificationsStore(); const selected=ref([]); const busy=ref(false); const calculationError=ref(''); const editing=ref(false); const occurredAt=ref(''); const correctionOpen=ref(false); const correctionReason=ref(''); const confirmation=ref(null)
const activity=computed(()=>activities.current); const attendeeIds=computed(()=>new Set(activity.value?.players?.map(p=>p.id)??[])); const available=computed(()=>guild.players.filter(p=>p.is_active&&!attendeeIds.value.has(p.id)))
const lootTotal=computed(()=>activity.value?.loot?.reduce((sum,item)=>sum+Number(item.quantity)*Number(item.unit_price),0)??0)
const participantShare=computed(()=>{const fixedShare=activity.value?.earnings?.[0]?.player_share;if(fixedShare!==undefined&&fixedShare!==null)return Number(fixedShare);const playerCount=activity.value?.players?.length??0;return playerCount?Math.floor(lootTotal.value/playerCount):0})
const distributedTotal=computed(()=>(activity.value?.players?.length??0)*participantShare.value)
const undistributedRemainder=computed(()=>Math.max(0,lootTotal.value-distributedTotal.value))
const correctionAllowed=computed(()=>activity.value?.earnings?.length>0&&activity.value.earnings.every(item=>item.status==='pending'&&!item.payout_id))
async function add(){if(!selected.value.length)return;busy.value=true;calculationError.value='';try{const count=selected.value.length;await activities.addPlayers(route.params.id,selected.value);selected.value=[];notifications.success(`Добавлено участников: ${count}.`)}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось добавить участников.');notifications.error(calculationError.value)}finally{busy.value=false}}
function togglePlayer(id){selected.value=selected.value.includes(id)?selected.value.filter(value=>value!==id):[...selected.value,id]}
async function remove(player){if(await confirmStore.ask({title:'Убрать участника?',message:`${player.nickname} будет исключён из этой активности.`,confirmLabel:'Убрать'}))await activities.removePlayer(route.params.id,player.id)}
async function removeLoot(item){if(!await confirmStore.ask({title:'Удалить лут из активности?',message:`«${item.item_name}» будет удалён, остаток в казне уменьшится на ${item.quantity} шт.`,confirmLabel:'Удалить',danger:true}))return;busy.value=true;calculationError.value='';try{await activities.removeLoot(route.params.id,item.id);notifications.success('Лут удалён из активности и казны.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось удалить лут.');notifications.error(calculationError.value)}finally{busy.value=false}}
async function editLootPrice(item){const value=await inputDialog.ask({title:'Исправить стоимость',message:`Укажите новую стоимость одной единицы «${item.item_name}».`,label:'Стоимость единицы',initialValue:item.unit_price,inputType:'number',min:0,step:1,confirmLabel:'Сохранить стоимость'});if(value===null)return;const price=Number(value);if(!Number.isInteger(price)||price<0){notifications.error('Стоимость должна быть целым неотрицательным числом.');return}busy.value=true;try{await activities.updateLootPrice(route.params.id,item.id,price);notifications.success('Стоимость предмета исправлена.')}catch(e){notifications.error(apiErrorMessage(e,'Не удалось изменить стоимость.'))}finally{busy.value=false}}
async function reopenForCorrection(){if(correctionReason.value.trim().length<10)return;busy.value=true;calculationError.value='';try{await activities.reopenActivity(route.params.id,correctionReason.value.trim());correctionOpen.value=false;correctionReason.value='';notifications.success('Начисления отменены. Исправьте данные и выполните расчёт заново.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось открыть активность для исправления.');notifications.error(calculationError.value)}finally{busy.value=false}}
function calculate(){confirmation.value={title:'Подтвердить расчёт',message:`Зафиксировать прайм: ${activity.value.players.length} участников получат по ${formatInteger(participantShare.value)}. Всего начислено ${formatInteger(distributedTotal.value)}, остаток оценки ${formatInteger(undistributedRemainder.value)}. Золотой баланс казны не изменится.`,confirmLabel:'Зафиксировать прайм',action:calculateConfirmed}}
async function calculateConfirmed(){confirmation.value=null;busy.value=true;calculationError.value='';try{await activities.calculatePrime(route.params.id);notifications.success('Нахрюк рассчитан, начисления сформированы.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось рассчитать нахрюк.');notifications.error(calculationError.value)}finally{busy.value=false}}
async function saveDraft(){busy.value=true;calculationError.value='';try{await activities.updateActivity(route.params.id,{occurred_at:moscowLocalToIso(occurredAt.value)});editing.value=false}catch(e){calculationError.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось сохранить черновик.'}finally{busy.value=false}}
async function deleteDraft(){if(!await confirmStore.ask({title:'Удалить черновик активности?',message:'Черновик будет удалён. Активность с лутом удалить нельзя.',confirmLabel:'Удалить',danger:true}))return;busy.value=true;calculationError.value='';try{await activities.deleteActivity(route.params.id);await router.push('/activities')}catch(e){calculationError.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Черновик с лутом удалить нельзя.';busy.value=false}}
onMounted(async()=>{await Promise.all([activities.fetchActivity(route.params.id),guild.fetchAllPlayers({active:true})]);occurredAt.value=formatMoscowDateTimeInput(activity.value.occurred_at)})
</script>
<template><section v-if="activity"><div class="panel activity-summary"><div class="activity-summary-image"><img v-if="activity.definition.icon_url" :src="activity.definition.icon_url" :alt="activity.definition.name"><span v-else>{{ activity.definition.name.slice(0,1) }}</span></div><div class="activity-summary-main"><p class="eyebrow">GAZ ARMORY · СОБЫТИЕ</p><div class="activity-summary-title"><h1>{{ activity.definition.name }}</h1><span :class="['event-type',activity.definition.type]">{{ activity.definition.type==='prime'?'Прайм':'Мини-прайм' }}</span></div><p class="muted">{{ formatDateTime(activity.occurred_at) }}</p><div class="activity-summary-metrics"><div><strong>{{ activity.players.length }}</strong><span>участников</span></div><div><strong>{{ formatInteger(lootTotal) }}</strong><span>стоимость лута</span></div><div><strong>{{ formatInteger(participantShare) }}</strong><span>на участника</span></div></div></div><div v-if="auth.canManage&&!activity.completed_at&&!activity.earnings.length" class="activity-summary-actions"><button class="secondary" @click="editing=!editing">{{ editing?'Отмена':'Изменить дату' }}</button><button class="danger" :disabled="busy" @click="deleteDraft">Удалить черновик</button></div></div><form v-if="editing" class="panel inline-edit activity-inline-edit" @submit.prevent="saveDraft"><label>Дата и время<input v-model="occurredAt" type="datetime-local" required></label><button class="primary" :disabled="busy">Сохранить</button></form>
  <div v-if="activity.definition.type==='prime'" class="calculate-bar activity-top-settlement"><div><strong v-if="activity.earnings.length">Нахрюк рассчитан: {{ formatInteger(activity.earnings[0].player_share) }} каждому</strong><strong v-else>К распределению: {{ formatInteger(lootTotal) }} оценки лута</strong><p class="muted">Участников: {{ activity.players.length }}<template v-if="activity.players.length"> · каждому: {{ formatInteger(participantShare) }} · начислено: {{ formatInteger(distributedTotal) }} · не распределено: {{ formatInteger(undistributedRemainder) }}</template></p><p class="settlement-note">Золотой баланс казны при расчёте не изменится.</p></div><div class="activity-settlement-actions"><button v-if="auth.canManage&&activity.earnings.length" class="danger" :disabled="busy||!correctionAllowed" :title="correctionAllowed?'Отменить начисления и исправить активность':'Исправление запрещено: начисления включены в нахрюк или выплачены'" @click="correctionOpen=true">Исправить расчёт</button><button v-if="auth.canManage&&!activity.earnings.length" class="primary" :disabled="busy||!activity.players.length||!activity.loot.length" @click="calculate">Рассчитать нахрюк</button></div></div>
  <div v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" class="participant-picker"><div class="attendee-picker"><button v-for="player in available" :key="player.id" type="button" :class="[`class-${player.class}`,{selected:selected.includes(player.id)}]" @click="togglePlayer(player.id)"><span class="attendee-check">{{ selected.includes(player.id)?'✓':'+' }}</span>{{ player.nickname }}</button><p v-if="!available.length" class="empty">Все активные игроки уже добавлены.</p></div><button class="primary add-attendees" :disabled="busy||!selected.length" @click="add">{{ busy?'Добавление…':`Добавить (${selected.length})` }}</button></div>
  <ManualLootForm v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" :activity-id="activity.id" />
  <div class="activity-content-grid"><div class="panel activity-loot-panel"><div class="panel-title"><h2>Полученный дроп</h2><span class="muted">{{ activity.loot?.length ?? 0 }} позиций</span></div><div v-if="activity.loot?.length" class="loot-cards"><article v-for="item in activity.loot" :key="item.id"><img v-if="item.icon_url" :src="item.icon_url" :alt="item.item_name"><div class="loot-icon-empty" v-else>?</div><div><strong>{{ item.item_name }}</strong><span>{{ item.quantity }} шт. × {{ formatInteger(item.unit_price) }} золота</span></div><b>{{ formatInteger(item.total_price) }}</b><div v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" class="loot-correction-actions"><button :disabled="busy" @click="editLootPrice(item)">Цена</button><button class="danger" :disabled="busy" title="Удалить лут из активности и уменьшить остаток казны" @click="removeLoot(item)">Удалить</button></div></article></div><p v-else class="empty">Дроп ещё не добавлен.</p></div><div class="panel activity-players-panel"><div class="panel-title"><h2>Участники</h2><span class="muted">{{ activity.players.length }}</span></div><div class="chips"><span v-for="player in activity.players" :key="player.id" :class="['player-chip',`class-${player.class}`]">{{ player.nickname }}<button v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" @click="remove(player)">×</button></span><p v-if="!activity.players.length" class="empty">Участники ещё не отмечены.</p></div></div></div>
  <p v-if="calculationError" class="notice error">{{ calculationError }}</p>
  <LootImportPanel v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" :activity-id="activity.id" />
  <AppModal :open="Boolean(confirmation)" :title="confirmation?.title??''" :dismissible="!busy" @close="confirmation=null"><div v-if="confirmation" class="form-card confirmation-card" role="alertdialog" aria-labelledby="confirmation-title"><p class="eyebrow">КОНТРОЛИРУЕМАЯ ОПЕРАЦИЯ</p><h2 id="confirmation-title">{{ confirmation.title }}</h2><p class="muted">{{ confirmation.message }}</p><div class="form-actions"><button type="button" @click="confirmation=null">Отмена</button><button type="button" class="primary" :disabled="busy" @click="confirmation.action">{{ confirmation.confirmLabel }}</button></div></div></AppModal>
  <AppModal :open="correctionOpen" title="Исправить завершённую активность" :dirty="Boolean(correctionReason.trim())" :dismissible="!busy" @close="correctionOpen=false"><form class="form-card correction-form" @submit.prevent="reopenForCorrection"><p class="eyebrow">КОНТРОЛИРУЕМАЯ ОПЕРАЦИЯ</p><h2>Исправить завершённую активность</h2><p class="muted">Pending-начисления будут удалены, а активность снова станет доступна для редактирования. После исправления участников или стоимости выполните расчёт повторно.</p><label>Причина исправления<textarea v-model="correctionReason" required minlength="10" maxlength="1000" rows="4" placeholder="Например: ошибочно отмечен участник или неверно указана стоимость предмета"></textarea></label><p class="correction-warning">Причина и ваш аккаунт сохранятся в журнале аудита. После выплаты операция запрещена.</p><div class="form-actions"><button type="button" @click="correctionOpen=false">Отмена</button><button class="danger" :disabled="busy||correctionReason.trim().length<10">{{ busy?'Отмена начислений…':'Отменить начисления и исправить' }}</button></div></form></AppModal>
</section><section v-else><p class="notice error" v-if="activities.error">{{ activities.error }}</p><p v-else class="empty">Загрузка…</p></section></template>
