<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
import { useActivitiesStore } from '../stores/activities.js'
import { useGuildStore } from '../stores/guild.js'
import LootImportPanel from '../components/LootImportPanel.vue'
import ManualLootForm from '../components/ManualLootForm.vue'
import { apiErrorMessage, useNotificationsStore } from '../stores/notifications.js'
const route=useRoute(); const router=useRouter(); const auth=useAuthStore(); const activities=useActivitiesStore(); const guild=useGuildStore(); const notifications=useNotificationsStore(); const selected=ref([]); const busy=ref(false); const calculationError=ref(''); const editing=ref(false); const occurredAt=ref('')
const activity=computed(()=>activities.current); const attendeeIds=computed(()=>new Set(activity.value?.players?.map(p=>p.id)??[])); const available=computed(()=>guild.players.filter(p=>p.is_active&&!attendeeIds.value.has(p.id)))
const lootTotal=computed(()=>activity.value?.loot?.reduce((sum,item)=>sum+Number(item.quantity)*Number(item.unit_price),0)??0)
async function add(){if(!selected.value.length)return;busy.value=true;calculationError.value='';try{const count=selected.value.length;await activities.addPlayers(route.params.id,selected.value);selected.value=[];notifications.success(`Добавлено участников: ${count}.`)}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось добавить участников.');notifications.error(calculationError.value)}finally{busy.value=false}}
function togglePlayer(id){selected.value=selected.value.includes(id)?selected.value.filter(value=>value!==id):[...selected.value,id]}
async function remove(player){if(confirm(`Убрать ${player.nickname} из участников?`))await activities.removePlayer(route.params.id,player.id)}
async function removeLoot(item){if(!confirm(`Удалить «${item.item_name}» из активности? Остаток в казне будет уменьшен на ${item.quantity} шт.`))return;busy.value=true;calculationError.value='';try{await activities.removeLoot(route.params.id,item.id);notifications.success('Лут удалён из активности и казны.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось удалить лут.');notifications.error(calculationError.value)}finally{busy.value=false}}
async function calculate(){if(!confirm(`Зафиксировать прайм и распределить ${lootTotal.value.toLocaleString('ru-RU')} золота?`))return;busy.value=true;calculationError.value='';try{await activities.calculatePrime(route.params.id);notifications.success('Нахрюк рассчитан, начисления сформированы.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось рассчитать нахрюк.');notifications.error(calculationError.value)}finally{busy.value=false}}
async function complete(){if(!confirm('Завершить мини-прайм? После этого изменить участников и лут будет нельзя.'))return;busy.value=true;calculationError.value='';try{await activities.completeActivity(route.params.id);notifications.success('Мини-прайм завершён, начисления сформированы.')}catch(e){calculationError.value=apiErrorMessage(e,'Не удалось завершить мини-прайм.');notifications.error(calculationError.value)}finally{busy.value=false}}
async function saveDraft(){busy.value=true;calculationError.value='';try{await activities.updateActivity(route.params.id,{occurred_at:new Date(occurredAt.value).toISOString()});editing.value=false}catch(e){calculationError.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось сохранить черновик.'}finally{busy.value=false}}
async function deleteDraft(){if(!confirm('Удалить этот черновик активности?'))return;busy.value=true;calculationError.value='';try{await activities.deleteActivity(route.params.id);await router.push('/activities')}catch(e){calculationError.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Черновик с лутом удалить нельзя.';busy.value=false}}
onMounted(async()=>{await Promise.all([activities.fetchActivity(route.params.id),guild.fetchPlayers()]);const date=new Date(activity.value.occurred_at);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());occurredAt.value=date.toISOString().slice(0,16)})
</script>
<template><section v-if="activity"><div class="page-heading"><div><p class="eyebrow">GAZ ARMORY · СОБЫТИЕ</p><h1>{{ activity.definition.name }}</h1><p class="muted">{{ new Date(activity.occurred_at).toLocaleString('ru-RU') }}</p></div><div v-if="auth.canManage&&!activity.completed_at&&!activity.earnings.length" class="form-actions"><button class="secondary" @click="editing=!editing">{{ editing?'Отмена':'Изменить дату' }}</button><button class="secondary" :disabled="busy" @click="deleteDraft">Удалить черновик</button></div></div><form v-if="editing" class="panel inline-edit" @submit.prevent="saveDraft"><label>Дата и время<input v-model="occurredAt" type="datetime-local" required></label><button class="primary" :disabled="busy">Сохранить</button></form>
  <div v-if="activity.definition.icon_url" class="activity-cover"><img :src="activity.definition.icon_url" :alt="activity.definition.name"><div><span>{{ activity.definition.type==='prime'?'Прайм':'Мини-прайм' }}</span><strong>{{ activity.definition.name }}</strong></div></div>
  <div class="metrics"><article><span>Тип</span><strong>{{ activity.definition.type==='prime'?'Прайм':'Мини-прайм' }}</strong></article><article><span>Участников</span><strong>{{ activity.players.length }}</strong></article><article v-if="activity.definition.type==='prime'"><span>Стоимость лута</span><strong>{{ activity.gold_value ?? 0 }}</strong></article></div>
  <div v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" class="participant-picker"><div class="attendee-picker"><button v-for="player in available" :key="player.id" type="button" :class="{selected:selected.includes(player.id)}" @click="togglePlayer(player.id)"><span class="attendee-check">{{ selected.includes(player.id)?'✓':'+' }}</span>{{ player.nickname }}</button><p v-if="!available.length" class="empty">Все активные игроки уже добавлены.</p></div><button class="primary add-attendees" :disabled="busy||!selected.length" @click="add">{{ busy?'Добавление…':`Добавить (${selected.length})` }}</button></div>
  <div class="panel"><h2>Участники</h2><div class="chips"><span v-for="player in activity.players" :key="player.id" class="player-chip">{{ player.nickname }}<button v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" @click="remove(player)">×</button></span><p v-if="!activity.players.length" class="empty">Участники ещё не отмечены.</p></div></div>
  <ManualLootForm v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" :activity-id="activity.id" />
  <div class="panel"><h2>Лут активности</h2><div v-if="activity.loot?.length" class="loot-cards"><article v-for="item in activity.loot" :key="item.id"><img v-if="item.icon_url" :src="item.icon_url" :alt="item.item_name"><div class="loot-icon-empty" v-else>?</div><div><strong>{{ item.item_name }}</strong><span>{{ item.quantity }} шт. × {{ Number(item.unit_price).toLocaleString('ru-RU') }} золота</span></div><b>{{ Number(item.total_price).toLocaleString('ru-RU') }}</b><button v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" class="loot-remove danger" :disabled="busy" title="Удалить лут из активности и уменьшить остаток казны" @click="removeLoot(item)">Удалить</button></article></div><p v-else class="empty">Лут ещё не добавлен.</p></div>
  <div v-if="activity.definition.type==='prime'" class="calculate-bar"><div><strong v-if="activity.earnings.length">Нахрюк рассчитан: {{ Number(activity.earnings[0].player_share).toLocaleString('ru-RU') }} каждому</strong><strong v-else>К распределению: {{ lootTotal.toLocaleString('ru-RU') }} золота</strong><p class="muted">Участников: {{ activity.players.length }}<template v-if="activity.players.length"> · доля: {{ Math.floor(lootTotal/activity.players.length).toLocaleString('ru-RU') }} · остаток: {{ (lootTotal%activity.players.length).toLocaleString('ru-RU') }}</template></p></div><button v-if="auth.canManage&&!activity.earnings.length" class="primary" :disabled="busy||!activity.players.length||!activity.loot.length" @click="calculate">Рассчитать нахрюк</button></div>
  <div v-else class="calculate-bar"><div><strong>{{ activity.completed_at?'Мини-прайм завершён':'Мини-прайм ещё редактируется' }}</strong><p class="muted">{{ activity.completed_at?'Посещение зафиксировано в профилях игроков.':'Добавьте участников и при необходимости лут, затем завершите активность.' }}</p></div><button v-if="auth.canManage&&!activity.completed_at" class="primary" :disabled="busy||!activity.players.length" @click="complete">{{ busy?'Завершение…':'Завершить мини-прайм' }}</button></div>
  <p v-if="calculationError" class="notice error">{{ calculationError }}</p>
  <LootImportPanel v-if="auth.canManage&&!activity.earnings.length&&!activity.completed_at" :activity-id="activity.id" />
</section><section v-else><p class="notice error" v-if="activities.error">{{ activities.error }}</p><p v-else class="empty">Загрузка…</p></section></template>
