<script setup>
import{onMounted,ref}from'vue';import{api}from'../api.js';import{apiErrorMessage}from'../stores/notifications.js';import AdminNav from'../components/AdminNav.vue';import SkeletonRows from'../components/SkeletonRows.vue'
const items=ref([]),loading=ref(true),error=ref(''),busy=ref(null)
async function load(){loading.value=true;error.value='';try{items.value=(await api.get('/api/activity-definitions')).data}catch(e){error.value=apiErrorMessage(e,'Не удалось загрузить активности.')}finally{loading.value=false}}
async function upload(item,file){if(!file||busy.value)return;busy.value=item.id;try{const body=new FormData();body.append('icon',file);body.append('updated_at',item.updated_at);Object.assign(item,(await api.post(`/api/activity-definitions/${item.id}/icon`,body)).data)}catch(e){error.value=apiErrorMessage(e,'Не удалось загрузить изображение.')}finally{busy.value=null}}
async function remove(item){if(busy.value||!confirm(`Удалить изображение «${item.name}»? Все созданные активности останутся без картинки.`))return;busy.value=item.id;try{Object.assign(item,(await api.delete(`/api/activity-definitions/${item.id}/icon`,{data:{updated_at:item.updated_at}})).data)}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=null}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">АДМИНКА</p><h1>Активности</h1><p class="muted">События и единые изображения для истории посещений</p></div><button :disabled="loading" @click="load">Обновить</button></div><AdminNav/><p v-if="error" class="notice error">{{ error }}</p><div class="panel activity-definition-icons"><SkeletonRows v-if="loading" :rows="6"/><div v-else class="definition-icon-grid"><article v-for="item in items" :key="item.id"><div class="definition-icon-preview"><img v-if="item.icon_url" :src="item.icon_url" :alt="item.name"><span v-else>{{ item.name.slice(0,1) }}</span></div><div><strong>{{ item.name }}</strong><small>{{ item.type==='prime'?'Прайм':'Мини-прайм' }}</small></div><label class="definition-upload"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" :disabled="busy" @change="upload(item,$event.target.files[0]);$event.target.value=''">{{ busy===item.id?'Загрузка…':item.icon_url?'Заменить':'Загрузить' }}</label><button v-if="item.icon_url" class="danger" :disabled="busy" @click="remove(item)">Удалить</button></article><div v-if="!items.length" class="empty-state"><strong>Справочник пуст</strong></div></div></div></section></template>
