<script setup>
import{onMounted,ref,watch}from'vue';import{useRoute,useRouter}from'vue-router';import{api}from'../api.js';import{useAuthStore}from'../stores/auth.js';import{apiErrorMessage}from'../stores/notifications.js';import AdminNav from'../components/AdminNav.vue';import SkeletonRows from'../components/SkeletonRows.vue';import PlayerAvatar from'../components/PlayerAvatar.vue'
const auth=useAuthStore(),route=useRoute(),router=useRouter(),users=ref([]),meta=ref({}),loading=ref(true),error=ref(''),busy=ref(null),search=ref(String(route.query.search??''));let timer
const labels={guild_leader:'ГЛ',micro_guild_leader:'Микро-ГЛ',developer:'Разработчик',party_leader:'PL',member:'Участник'}
async function load(){loading.value=true;error.value='';try{const{data}=await api.get('/api/admin/users',{params:{search:route.query.search||undefined,page:route.query.page||1}});users.value=data.data;meta.value={current_page:data.current_page,last_page:data.last_page,total:data.total};}catch(e){error.value=apiErrorMessage(e,'Не удалось загрузить пользователей.')}finally{loading.value=false}}
function apply(page=1){router.replace({query:{...(search.value?{search:search.value}:{}),...(page>1?{page}: {})}})}
watch(search,()=>{clearTimeout(timer);timer=setTimeout(()=>apply(),350)});watch(()=>route.query,load,{deep:true});onMounted(load)
async function toggleRole(user,role,checked){if(busy.value)return;const current=user.roles?.length?[...user.roles]:[user.role],roles=checked?[...new Set([...current,role])]:current.filter(value=>value!==role);if(!roles.length){error.value='У пользователя должна остаться хотя бы одна роль.';return}busy.value=user.id;try{const{data}=await api.patch(`/api/admin/users/${user.id}/roles`,{roles,updated_at:user.updated_at});Object.assign(user,data);if(user.id===auth.user?.id)await auth.fetchMe()}catch(e){error.value=apiErrorMessage(e,'Не удалось изменить права.');await load()}finally{busy.value=null}}
function roleDisabled(user,role){if(busy.value===user.id)return true;if(auth.canAssignElevatedRoles)return false;return['guild_leader','developer'].includes(role)||(user.roles??[user.role]).some(value=>['guild_leader','developer'].includes(value))}
async function action(user,type){if(busy.value)return;const messages={unlink:`Отвязать «${user.player?.nickname}»? Персонаж и вся история сохранятся.`,deactivate:`Ликвидировать «${user.player?.nickname}»? Профиль исчезнет из активного состава, история сохранится.`,activate:`Вернуть «${user.player?.nickname}» в активный состав?`,delete:`Удалить Discord-пользователя @${user.discord_username}? Персонаж будет отвязан, история сохранится.`};if(!confirm(messages[type]))return;busy.value=user.id;error.value='';try{if(type==='unlink')await api.put(`/api/players/${user.player.id}/user`,{user_id:null});if(type==='deactivate')await api.delete(`/api/players/${user.player.id}`);if(type==='activate')await api.post(`/api/players/${user.player.id}/activate`);if(type==='delete')await api.delete(`/api/admin/users/${user.id}`);await load()}catch(e){error.value=apiErrorMessage(e,'Операция не выполнена.')}finally{busy.value=null}}
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">АДМИНКА</p><h1>Пользователи и роли</h1><p class="muted">Управление аккаунтами и минимально необходимыми правами</p></div><span class="freshness">Всего: {{ meta.total??0 }}</span></div><AdminNav/><div class="panel admin-users-panel"><input v-model.trim="search" class="admin-user-search" type="search" placeholder="Поиск по Discord или персонажу"><p v-if="error" class="notice error">{{ error }} <button @click="load">Повторить</button></p><SkeletonRows v-if="loading" :rows="7" :columns="4"/><div v-else class="admin-user-list"><article v-for="user in users" :key="user.id" class="admin-user-row"><PlayerAvatar class="admin-user-avatar" :player="{nickname:user.discord_display_name||user.discord_username,user}" size="small"/><div class="admin-user-identity"><strong>{{ user.discord_display_name||user.discord_username }}</strong><small>@{{ user.discord_username }}</small></div><div class="admin-user-player"><RouterLink v-if="user.player" :to="`/players/${user.player.id}`">{{ user.player.nickname }}</RouterLink><span v-else>Профиль не привязан</span><small>{{ user.player?.group?.name??(user.player?'Одиночка':'') }}</small></div><div class="admin-role-select"><span>Права доступа</span><label v-for="(label,value) in labels" :key="value"><input type="checkbox" :checked="(user.roles??[user.role]).includes(value)" :disabled="roleDisabled(user,value)" @change="toggleRole(user,value,$event.target.checked)">{{ label }}</label></div><details class="admin-actions-menu"><summary>Действия</summary><div><button :disabled="!user.player||busy" @click="action(user,'unlink')">Отвязать Discord</button><button v-if="user.player?.is_active" class="danger" :disabled="busy" @click="action(user,'deactivate')">Ликвидировать</button><button v-else-if="user.player" :disabled="busy" @click="action(user,'activate')">Восстановить</button><button class="danger" :disabled="user.id===auth.user?.id||busy" @click="action(user,'delete')">Удалить пользователя</button></div></details></article><div v-if="!users.length" class="empty-state"><strong>Пользователи не найдены</strong><p>Измените строку поиска.</p></div></div><div v-if="meta.last_page>1" class="audit-pagination"><button :disabled="meta.current_page<=1||loading" @click="apply(meta.current_page-1)">Назад</button><span>{{ meta.current_page }} из {{ meta.last_page }}</span><button :disabled="meta.current_page>=meta.last_page||loading" @click="apply(meta.current_page+1)">Далее</button></div></div></section></template>
