<script setup>
import{onMounted,ref}from'vue';import{api}from'../api.js';import AdminNav from'../components/AdminNav.vue';import SkeletonRows from'../components/SkeletonRows.vue';import{apiErrorMessage}from'../stores/notifications.js';import{useAuthStore}from'../stores/auth.js'
const items=ref([]),loading=ref(true),error=ref(''),busy=ref(null)
const auth=useAuthStore()
async function load(){loading.value=true;error.value='';try{items.value=(await api.get('/api/admin/player-link-requests')).data}catch(e){error.value=apiErrorMessage(e,'Не удалось загрузить заявки.')}finally{loading.value=false}}
async function review(item,decision){if(busy.value)return;busy.value=item.id;error.value='';try{await api.post(`/api/admin/player-link-requests/${item.id}/${decision}`);items.value=items.value.filter(row=>row.id!==item.id)}catch(e){error.value=apiErrorMessage(e,'Не удалось обработать заявку.')}finally{busy.value=null}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">{{ auth.isPartyLeader&&!auth.canAdmin?'РАЗДЕЛ ПЛ':'УПРАВЛЕНИЕ ГИЛЬДИЕЙ' }}</p><h1>{{ auth.isPartyLeader&&!auth.canAdmin?'Заявки на вход':'Заявки' }}</h1><p class="muted">{{ auth.isPartyLeader&&!auth.canAdmin?'Здесь вы подтверждаете игроков, которые хотят вступить именно в вашу КП.':'Подтверждение Discord-пользователей и персонажей' }}</p></div><button :disabled="loading" @click="load">Обновить список</button></div><div v-if="auth.isPartyLeader&&!auth.canAdmin" class="leader-help panel"><div class="leader-help-icon">✓</div><div><strong>Что здесь делать?</strong><p>Проверьте никнейм и класс игрока. Если готовы принять его в КП — нажмите «Принять в КП». Если заявка не подходит — «Отклонить».</p></div></div><AdminNav v-if="auth.canAdmin"/><p v-if="error" class="notice error">{{ error }} <button @click="load">Повторить</button></p><div class="panel"><SkeletonRows v-if="loading" :rows="4"/><div v-else-if="items.length" class="link-request-list"><article v-for="item in items" :key="item.id" class="link-request-card"><div><strong>{{ item.user?.discord_display_name||item.user?.discord_username }}</strong><small>Discord: @{{ item.user?.discord_username }}</small></div><span class="request-arrow">просит вход</span><div><strong>{{ item.player?.nickname }}</strong><small>{{ item.player?.class }} · {{ item.requested_group?.name || 'Сольник' }}</small></div><div class="link-request-actions"><button class="primary" :disabled="busy" @click="review(item,'approve')">{{ item.requested_group_id?'Принять в КП':'Подтвердить сольника' }}</button><button class="danger" :disabled="busy" @click="review(item,'reject')">Отклонить</button></div></article></div><div v-else class="empty-state"><strong>Новых заявок нет</strong><p>{{ auth.isPartyLeader&&!auth.canAdmin?'Когда игрок выберет вашу КП при регистрации, его заявка появится здесь.':'Все запросы на вход обработаны.' }}</p></div></div></section></template>
