<script setup>
import{onMounted,ref}from'vue';import{api}from'../api.js';import{apiErrorMessage}from'../stores/notifications.js';import AdminNav from'../components/AdminNav.vue';import SkeletonRows from'../components/SkeletonRows.vue'
const items=ref([]),loading=ref(true),busy=ref(false),error=ref(''),name=ref(''),icon=ref(null),fileInput=ref(null)
async function load(){loading.value=true;error.value='';try{items.value=(await api.get('/api/loot-catalog')).data}catch(e){error.value=apiErrorMessage(e,'Не удалось загрузить лут.')}finally{loading.value=false}}
async function add(){if(busy.value)return;busy.value=true;error.value='';try{const body=new FormData();body.append('name',name.value);body.append('icon',icon.value);await api.post('/api/loot-catalog',body);name.value='';icon.value=null;if(fileInput.value)fileInput.value.value='';await load()}catch(e){error.value=apiErrorMessage(e,'Не удалось добавить предмет.')}finally{busy.value=false}}
async function remove(item){if(busy.value||!confirm(`Убрать «${item.name}» из справочника? Остатки и история предмета сохранятся.`))return;busy.value=true;try{await api.delete(`/api/loot-catalog/${item.id}`,{data:{updated_at:item.updated_at}});items.value=items.value.filter(row=>row.id!==item.id)}catch(e){error.value=apiErrorMessage(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">АДМИНКА</p><h1>Справочник лута</h1><p class="muted">Предметы, доступные при заведении дропа</p></div></div><AdminNav/><p v-if="error" class="notice error">{{ error }} <button @click="load">Повторить</button></p><div class="panel catalog-panel"><SkeletonRows v-if="loading" :rows="5"/><div v-else-if="items.length" class="catalog-grid"><article v-for="item in items" :key="item.id"><img :src="item.icon_url" :alt="item.name"><strong>{{ item.name }}</strong><button class="danger" :disabled="busy" @click="remove(item)">×</button></article></div><div v-else class="empty-state"><strong>Предметов пока нет</strong><p>Добавьте первый предмет ниже.</p></div></div><div class="panel admin-catalog-create"><h2>Добавить предмет</h2><form class="catalog-admin-form" @submit.prevent="add"><label>Название<input v-model.trim="name" required maxlength="255"></label><label>Иконка<input ref="fileInput" type="file" required accept="image/png,image/jpeg,image/webp,image/gif" @change="icon=$event.target.files[0]??null"></label><button class="primary" :disabled="busy||!icon">{{ busy?'Добавление…':'Добавить предмет' }}</button></form></div></section></template>
