<script setup>
import { computed,onMounted,onUnmounted,ref } from 'vue';import { useRoute } from 'vue-router';import { api } from '../api.js';import { useAuthStore } from '../stores/auth.js';import { apiErrorMessage,useNotificationsStore } from '../stores/notifications.js';import TokenAmount from '../components/TokenAmount.vue';import PlayerAvatar from '../components/PlayerAvatar.vue'
const route=useRoute();const auth=useAuthStore();const notifications=useNotificationsStore();const lot=ref(null);const amount=ref(0);const busy=ref(false);const error=ref('');const topBid=computed(()=>lot.value?.bids?.[0]??null);const minimumBid=computed(()=>topBid.value?Number(topBid.value.amount)+Number(lot.value.minimum_step):Number(lot.value?.starting_bid??0));const ended=computed(()=>lot.value?new Date(lot.value.ends_at)<=new Date():false)
const displayDateTime=date=>new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',dateStyle:'short',timeStyle:'medium'}).format(new Date(date))
async function load(){try{lot.value=(await api.get(`/api/auctions/${route.params.id}`)).data;if(Number(amount.value)<minimumBid.value)amount.value=minimumBid.value}catch(e){error.value=e.response?.data?.message??'Не удалось загрузить лот.'}}
async function bid(){busy.value=true;error.value='';try{await api.post(`/api/auctions/${lot.value.id}/bid`,{amount:amount.value});await load();notifications.success('Ставка принята.')}catch(e){error.value=apiErrorMessage(e,'Ставка отклонена.');notifications.error(error.value)}finally{busy.value=false}}
async function finish(){busy.value=true;error.value='';try{await api.post(`/api/auctions/${lot.value.id}/finish`);await load();notifications.success('Аукцион завершён.')}catch(e){error.value=apiErrorMessage(e,'Не удалось завершить аукцион.');notifications.error(error.value)}finally{busy.value=false}}
async function cancel(){if(!confirm('Отменить лот и вернуть предмет в свободный остаток?'))return;busy.value=true;try{await api.post(`/api/auctions/${lot.value.id}/cancel`);await load();notifications.warning('Лот отменён, предмет возвращён в казну.')}catch(e){error.value=apiErrorMessage(e,'Не удалось отменить лот.');notifications.error(error.value)}finally{busy.value=false}};let liveTicker;onMounted(()=>{load();liveTicker=setInterval(load,5000)});onUnmounted(()=>clearInterval(liveTicker))
</script>
<template>
  <section v-if="lot">
    <div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · АУКЦИОН #{{ lot.id }}</p><h1>{{ lot.item.item_name }}</h1><p class="muted">{{ lot.quantity }} шт. · до {{ displayDateTime(lot.ends_at) }} МСК</p></div><RouterLink class="secondary" to="/auctions">К списку лотов</RouterLink></div>
    <div class="auction-detail"><div class="panel lot-main"><div class="lot-item"><img v-if="lot.item.icon_url" :src="lot.item.icon_url"><div class="loot-icon-empty" v-else>?</div><div><span class="muted">Текущая ставка</span><strong><TokenAmount :value="Number(topBid?.amount??lot.starting_bid).toLocaleString('ru-RU')"/></strong><span v-if="topBid" class="auction-leader-badge"><span aria-hidden="true">♛</span><PlayerAvatar :player="topBid.player" size="small"/><small>Лидер</small><b>{{ topBid.player.nickname }}</b></span><small v-else>Ставок пока нет</small></div></div>
      <form v-if="lot.status==='active'&&!ended" class="bid-form" @submit.prevent="bid"><label>Ваша максимальная ставка, жетоны<input v-model.number="amount" type="number" :min="minimumBid" step="1" required></label><span class="muted">Минимум {{ minimumBid.toLocaleString('ru-RU') }} жет. · шаг {{ Number(lot.minimum_step).toLocaleString('ru-RU') }} жет. · автопродление {{ lot.extension_minutes }} мин.</span><button class="primary" :disabled="busy||!auth.user?.player">Установить максимум</button></form>
      <div v-else class="auction-result"><strong v-if="lot.status==='finished'&&lot.winner">Победитель: {{ lot.winner.nickname }} · <TokenAmount :value="Number(lot.winning_bid).toLocaleString('ru-RU')"/></strong><strong v-else-if="lot.status==='finished'">Завершён без ставок</strong><strong v-else-if="lot.status==='cancelled'">Лот отменён</strong><strong v-else-if="ended">Приём ставок завершён</strong><strong v-else>Черновик</strong></div>
      <p v-if="error" class="notice error">{{ error }}</p><div v-if="auth.canCreateAuctions&&['draft','active'].includes(lot.status)" class="lot-admin-actions"><button v-if="lot.status==='active'&&ended" class="primary" :disabled="busy" @click="finish">Подвести итог</button><button class="secondary" :disabled="busy" @click="cancel">Отменить</button></div></div>
      <div class="panel"><div class="panel-title"><h2>История ставок</h2><span class="muted">{{ lot.bids.length }}</span></div><div v-if="lot.bids.length" class="bid-history"><div v-for="(entry,index) in lot.bids" :key="entry.id" :class="{ 'top-bid-row': index === 0 }"><strong class="bid-player"><PlayerAvatar :player="entry.player" size="tiny"/><span>{{ entry.player.nickname }}</span><em v-if="index === 0">♛ лидер</em></strong><b><TokenAmount :value="Number(entry.amount).toLocaleString('ru-RU')"/></b><time>{{ new Date(entry.created_at).toLocaleString('ru-RU') }}</time></div></div><p v-else class="empty">Ставок пока нет.</p></div>
    </div>
  </section>
  <section v-else><p :class="error?'notice error':'empty'">{{ error||'Загрузка…' }}</p></section>
</template>
