<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { api } from '../api.js';import { useAuthStore } from '../stores/auth.js'
const auth=useAuthStore();const auctions=ref([]);const items=ref([]);const showForm=ref(false);const editingId=ref(null);const error=ref('');const busy=ref(false);const form=reactive({treasury_item_id:'',quantity:1,starting_bid:0,minimum_step:1,ends_at:''})
const activeCount=computed(()=>auctions.value.filter(x=>x.status==='active').length)
function localDateTime(date){const value=new Date(date);value.setMinutes(value.getMinutes()-value.getTimezoneOffset());return value.toISOString().slice(0,16)}
function openForm(){editingId.value=null;Object.assign(form,{treasury_item_id:'',quantity:1,starting_bid:0,minimum_step:1,ends_at:localDateTime(new Date(Date.now()+60*60*1000))});error.value='';showForm.value=true}
function editDraft(lot){editingId.value=lot.id;Object.assign(form,{treasury_item_id:lot.treasury_item_id,quantity:Number(lot.quantity),starting_bid:Number(lot.starting_bid),minimum_step:Number(lot.minimum_step),ends_at:localDateTime(new Date(lot.ends_at)>new Date()?lot.ends_at:new Date(Date.now()+60*60*1000))});error.value='';showForm.value=true}
async function loadAll(){const [a,t]=await Promise.all([api.get('/api/auctions'),api.get('/api/treasury')]);auctions.value=a.data;items.value=t.data.items;window.dispatchEvent(new CustomEvent('auction-count-changed',{detail:activeCount.value}))}
async function save(){busy.value=true;error.value='';try{const payload={...form,treasury_item_id:Number(form.treasury_item_id),ends_at:new Date(form.ends_at).toISOString()};if(editingId.value)await api.put(`/api/auctions/${editingId.value}`,payload);else await api.post('/api/auctions',payload);showForm.value=false;await loadAll()}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось сохранить лот.'}finally{busy.value=false}}
async function start(id){try{await api.post(`/api/auctions/${id}/start`);await loadAll()}catch(e){error.value=e.response?.data?.message??'Не удалось запустить лот.'}}
onMounted(loadAll)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · АУКЦИОН</p><h1>Аукцион гильдии</h1></div><button v-if="auth.canManage" class="primary" @click="openForm">Добавить лот</button></div>
  <span class="count-badge">{{ activeCount }} активных лотов</span><p v-if="error&&!showForm" class="notice error">{{ error }}</p><div class="auction-grid"><article v-for="lot in auctions" :key="lot.id" class="panel auction-lot"><RouterLink class="auction-item-link" :to="`/auctions/${lot.id}`"><img v-if="lot.item.icon_url" :src="lot.item.icon_url"><div><strong>{{ lot.item.item_name }}</strong><p class="muted">{{ lot.quantity }} шт. · старт {{ Number(lot.starting_bid).toLocaleString('ru-RU') }} 🪙</p></div></RouterLink><span :class="['import-status',lot.status==='active'?'confirmed':'draft']">{{ {draft:'Черновик',active:'Активен',finished:'Завершён',cancelled:'Отменён'}[lot.status] }}</span><div class="auction-leader"><span>Максимальная ставка</span><strong v-if="lot.top_bid">{{ Number(lot.top_bid.amount).toLocaleString('ru-RU') }} 🪙</strong><strong v-else>—</strong><small v-if="lot.top_bid">Лидер: {{ lot.top_bid.player.nickname }}</small><small v-else>Ставок пока нет</small></div><p class="muted">Ставок: {{ lot.bids_count }} · до {{ new Date(lot.ends_at).toLocaleString('ru-RU') }}</p><div v-if="auth.canManage&&lot.status==='draft'" class="draft-actions"><button class="secondary" @click="editDraft(lot)">Редактировать</button><button class="primary" @click="start(lot.id)">Запустить</button></div><RouterLink v-else class="secondary lot-open" :to="`/auctions/${lot.id}`">Открыть</RouterLink></article><div v-if="!auctions.length" class="panel auction-empty"><div class="auction-icon">◇</div><h2>Лотов нет</h2><p class="muted">ГЛ или Разработчик может выставить предмет из казны.</p></div></div>
  <div v-if="showForm" class="modal" @click.self="showForm=false"><form class="form-card" @submit.prevent="save"><h2>{{ editingId?'Редактировать черновик':'Новый лот' }}</h2><label>Предмет<select v-model="form.treasury_item_id" required><option value="" disabled>Выберите из казны</option><option v-for="item in items" :key="item.id" :value="item.id">{{ item.item_name }} · доступно {{ item.available_quantity }}</option></select></label><label>Количество<input v-model.number="form.quantity" type="number" min="1" required></label><label>Стартовая ставка<input v-model.number="form.starting_bid" type="number" min="0" required></label><label>Минимальный шаг<input v-model.number="form.minimum_step" type="number" min="1" required></label><label>Завершение<input v-model="form.ends_at" type="datetime-local" :min="localDateTime(new Date())" required></label><p v-if="error" class="notice error">{{ error }}</p><div class="form-actions"><button type="button" @click="showForm=false">Отмена</button><button class="primary" :disabled="busy">{{ editingId?'Сохранить':'Создать черновик' }}</button></div></form></div>
</section></template>
