<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api.js'
import { useAuthStore } from '../stores/auth.js'
import GoldAmount from '../components/GoldAmount.vue'

const route = useRoute(), router = useRouter(), auth = useAuthStore()
const payout = ref(null), search = ref(''), loading = ref(true), busy = ref(false), error = ref('')
const amountBusy = ref(null)
const statusLabels = { draft: 'Черновик', calculated: 'Рассчитан', paid: 'Выплачен', cancelled: 'Отменён' }
const players = computed(() => (payout.value?.players ?? []).filter(player => player.nickname_snapshot.toLowerCase().includes(search.value.toLowerCase())))
async function load() { loading.value=true;error.value='';try{payout.value=(await api.get(`/api/payouts/${route.params.id}`)).data}catch(e){error.value=e.response?.status===403?'У вас нет доступа к этой выплате.':'Не удалось загрузить выплату.'}finally{loading.value=false} }
async function action(name) { if(!confirm(name==='complete'?'Подтвердить фактическую выплату золота всем участникам?':name==='cancel'?'Отменить эту выплату?':'Рассчитать выплату?'))return;busy.value=true;error.value='';try{await api.post(`/api/payouts/${payout.value.id}/${name}`);await load()}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Операция не выполнена.'}finally{busy.value=false} }
async function saveAmount(player) { amountBusy.value=player.id;error.value='';try{const {data}=await api.patch(`/api/payouts/${payout.value.id}/players/${player.id}`,{amount:Number(player.amount)});player.amount=data.player.amount;payout.value.total_amount=data.total_amount}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось изменить сумму.';await load()}finally{amountBusy.value=null} }
async function removeDraft() { if(!confirm('Удалить этот черновик нахрюка?'))return;busy.value=true;error.value='';try{await api.delete(`/api/payouts/${payout.value.id}`);await router.push('/payouts')}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось удалить черновик.'}finally{busy.value=false} }
function date(value,withTime=false){if(!value)return'—';return new Date(value).toLocaleString('ru-RU',withTime?{}:{dateStyle:'short'})}
onMounted(load)
</script>

<template><section>
  <div v-if="loading" class="panel empty">Загрузка выплаты…</div>
  <template v-else-if="payout">
    <div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · НАХРЮК</p><h1>Нахрюк #{{ payout.id }}</h1><p class="muted">{{ date(payout.period_from) }} — {{ date(payout.period_to) }}</p></div><div v-if="auth.canManage" class="page-actions"><button v-if="payout.status==='draft'" class="primary" :disabled="busy" @click="action('calculate')">Продолжить и рассчитать</button><button v-if="payout.status==='draft'" class="danger" :disabled="busy" @click="removeDraft">Удалить черновик</button><button v-if="payout.status==='calculated'" class="primary" :disabled="busy" @click="action('complete')">Подтвердить выплату</button><button v-if="payout.status==='calculated'" class="secondary" :disabled="busy" @click="action('cancel')">Отменить</button></div></div>
    <p v-if="error" class="notice error">{{ error }}</p>
    <div class="payout-summary-grid"><div class="panel"><span>Статус</span><strong :class="['import-status',payout.status==='paid'?'confirmed':'draft']">{{ statusLabels[payout.status] }}</strong></div><div class="panel"><span>Общая сумма</span><strong><GoldAmount :value="Number(payout.total_amount).toLocaleString('ru-RU')"/></strong></div><div class="panel"><span>Участников</span><strong>{{ payout.players.length }}</strong></div><div class="panel"><span>Создал</span><strong>{{ payout.creator?.discord_display_name || payout.creator?.discord_username || 'Система' }}</strong></div><div class="panel"><span>Рассчитан</span><strong>{{ date(payout.calculated_at,true) }}</strong></div><div class="panel"><span>Выплачен</span><strong>{{ date(payout.paid_at,true) }}</strong></div></div>
    <div class="panel payout-player-panel"><div class="panel-title"><div><h2>Участники выплаты</h2><p class="muted">До выплаты суммы можно скорректировать вручную</p></div><input v-model.trim="search" placeholder="Поиск по никнейму"></div><div class="table-wrap flat"><table><thead><tr><th>Никнейм</th><th>Посещение праймов</th><th>Праймы</th><th>Мини-праймы</th><th>Статус</th><th class="right">Сумма</th></tr></thead><tbody><tr v-for="player in players" :key="player.id"><td><strong>{{ player.nickname_snapshot }}</strong></td><td>{{ Number(player.prime_attendance_percentage_snapshot).toLocaleString('ru-RU') }}%</td><td>{{ player.primes_count }}</td><td>{{ player.mini_activities_count }}</td><td><span :class="['import-status',player.status==='paid'?'confirmed':'draft']">{{ {pending:'Ожидает',paid:'Выплачено',cancelled:'Отменено'}[player.status] }}</span></td><td class="right transaction-amount"><div v-if="auth.canManage&&payout.status==='calculated'" class="payout-amount-editor"><input v-model.number="player.amount" type="number" min="0" step="1"><button :disabled="amountBusy===player.id" @click="saveAmount(player)">Сохранить</button></div><GoldAmount v-else :value="Number(player.amount).toLocaleString('ru-RU')"/></td></tr><tr v-if="!players.length"><td colspan="6" class="empty">Участники не найдены.</td></tr></tbody></table></div></div>
    <div class="panel payout-activity-panel"><div class="panel-title"><h2>Включённые активности</h2><span class="muted">{{ payout.activities.length }}</span></div><div v-if="payout.activities.length" class="payout-activity-list"><RouterLink v-for="activity in payout.activities" :key="activity.id" :to="`/activities/${activity.id}`"><div><strong>{{ activity.definition?.name }}</strong><small>{{ date(activity.occurred_at,true) }}</small></div><span>{{ activity.definition?.type==='mini_activity'?'Мини-прайм':'Прайм' }}</span><b><GoldAmount :value="Number(activity.gold_value).toLocaleString('ru-RU')"/></b></RouterLink></div><p v-else class="empty">Активности появятся после расчёта.</p></div>
    <p v-if="['paid','cancelled'].includes(payout.status)" class="notice">Завершённая выплата защищена от изменений.</p>
  </template>
  <div v-else class="panel"><p class="notice error">{{ error }}</p><RouterLink class="secondary" to="/payouts">Вернуться к выплатам</RouterLink></div>
</section></template>
