<script setup>
import { computed, onMounted, ref } from 'vue'
import { api } from '../api.js'
import StatCard from '../components/StatCard.vue'
import { useAuthStore } from '../stores/auth.js'
import { apiErrorMessage,useNotificationsStore } from '../stores/notifications.js'
const auth=useAuthStore();const notifications=useNotificationsStore();const data=ref({summary:{gold:0,primes:0,mini_activities:0,participants:0},players:[]});const payouts=ref([]);const search=ref('');const error=ref('');const showForm=ref(false);const from=ref('');const to=ref('');const busy=ref(false);const expanded=ref(null)
const rows=computed(()=>data.value.players.filter(row=>row.nickname.toLowerCase().includes(search.value.toLowerCase())))
async function load(){try{const [pending,batches]=await Promise.all([api.get('/api/earnings/pending'),api.get('/api/payouts')]);data.value=pending.data;payouts.value=batches.data}catch(e){error.value=e.response?.data?.message??'Не удалось загрузить начисления.'}}
async function create(){busy.value=true;error.value='';try{const payout=(await api.post('/api/payouts',{period_from:from.value,period_to:to.value})).data;await api.post(`/api/payouts/${payout.id}/calculate`);showForm.value=false;await load();notifications.success('Нахрюк создан и рассчитан.')}catch(e){error.value=apiErrorMessage(e,'Не удалось рассчитать выплату.');notifications.error(error.value)}finally{busy.value=false}}
async function action(id,name){busy.value=true;error.value='';try{await api.post(`/api/payouts/${id}/${name}`);await load();notifications.success(name==='complete'?'Нахрюк отмечен выплаченным.':name==='cancel'?'Нахрюк отменён.':'Нахрюк пересчитан.')}catch(e){error.value=apiErrorMessage(e);notifications.error(error.value)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · НАХРЮК</p><h1>Нахрюк</h1><p class="muted">Начисления за фактически посещённые праймы и мини-праймы</p></div><button v-if="auth.canManage" class="primary" @click="showForm=true">Создать выплату</button></div>
  <div class="stats-row four"><StatCard label="Золото на расплит" :value="Number(data.summary.gold).toLocaleString('ru-RU')" accent/><StatCard label="Праймов" :value="data.summary.primes"/><StatCard label="Мини-активностей" :value="data.summary.mini_activities"/><StatCard label="Участников" :value="data.summary.participants"/></div>
  <p v-if="error" class="notice error">{{ error }}</p><div class="panel"><div class="panel-title"><h2>Ожидаемые начисления</h2><input v-model="search" placeholder="Поиск по нику…"></div><div class="table-wrap flat"><table><thead><tr><th>Ник</th><th>Праймы</th><th>Мини-праймы</th><th class="right">Общая сумма</th></tr></thead><tbody><tr v-for="row in rows" :key="row.player_id"><td>{{ row.nickname }}</td><td>{{ row.primes_count }}</td><td>{{ row.mini_activities_count }}</td><td class="right">{{ Number(row.amount).toLocaleString('ru-RU') }} золота</td></tr><tr v-if="!rows.length"><td colspan="4" class="empty">Начислений пока нет.</td></tr></tbody></table></div></div>
  <div class="panel payout-batches"><div class="panel-title"><h2>Партии выплат</h2><span class="muted">{{ payouts.length }}</span></div><article v-for="payout in payouts" :key="payout.id" class="payout-batch"><div><strong>Нахрюк #{{ payout.id }}</strong><span>{{ new Date(payout.period_from).toLocaleDateString('ru-RU') }} — {{ new Date(payout.period_to).toLocaleDateString('ru-RU') }}</span></div><b>{{ Number(payout.total_amount).toLocaleString('ru-RU') }} 🪙</b><span :class="['import-status',payout.status==='paid'?'confirmed':'draft']">{{ {draft:'Черновик',calculated:'Рассчитан',paid:'Выплачен',cancelled:'Отменён'}[payout.status] }}</span><div class="batch-actions"><button class="secondary" @click="expanded=expanded===payout.id?null:payout.id">{{ expanded===payout.id?'Скрыть':'Подробнее' }}</button><template v-if="auth.canManage&&payout.status==='calculated'"><button class="primary" :disabled="busy" @click="action(payout.id,'complete')">Подтвердить выплату</button><button class="secondary" :disabled="busy" @click="action(payout.id,'cancel')">Отменить</button></template></div><div v-if="expanded===payout.id" class="payout-details"><div><h3>События</h3><RouterLink v-for="activity in payout.activities" :key="activity.id" :to="`/activities/${activity.id}`">{{ activity.definition?.name }} <small>{{ activity.definition?.type==='mini_activity'?'Мини-прайм':'Прайм' }}</small></RouterLink><p v-if="!payout.activities?.length" class="empty">События ещё не рассчитаны.</p></div><div><h3>Участники</h3><span v-for="player in payout.players" :key="player.id"><strong>{{ player.nickname_snapshot }}</strong><small>{{ player.primes_count }} прайм. · {{ player.mini_activities_count }} мини</small><b>{{ Number(player.amount).toLocaleString('ru-RU') }} 🪙</b></span></div></div></article><p v-if="!payouts.length" class="empty">Партий выплат пока нет.</p></div>
  <div v-if="payouts.length" class="payout-page-links"><span class="muted">Открыть полную карточку:</span><RouterLink v-for="payout in payouts" :key="payout.id" :to="`/payouts/${payout.id}`">Нахрюк #{{ payout.id }}</RouterLink></div>
  <div v-if="showForm" class="modal" @click.self="showForm=false"><form class="form-card" @submit.prevent="create"><h2>Новая выплата</h2><label>Период с<input v-model="from" type="date" required></label><label>Период по<input v-model="to" type="date" :min="from" required></label><p class="muted">В выплату попадут все свободные начисления за выбранный период.</p><p v-if="error" class="notice error">{{ error }}</p><div class="form-actions"><button type="button" @click="showForm=false">Отмена</button><button class="primary" :disabled="busy">Рассчитать</button></div></form></div>
</section></template>
