<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api.js'
import { useAuthStore } from '../stores/auth.js'
import GoldAmount from '../components/GoldAmount.vue'
import TokenAmount from '../components/TokenAmount.vue'

const route = useRoute(), router = useRouter(), auth = useAuthStore()
const payout = ref(null), search = ref(''), statusFilter=ref(''), selected=ref([]), loading = ref(true), busy = ref(false), error = ref(''), exporting=ref('')
const statusLabels = { draft: 'Черновик', calculated: 'Рассчитан', paid: 'Выплачен', cancelled: 'Отменён' }
const statusDescriptions = { draft: 'Период создан, начисления ещё не зафиксированы', calculated: 'Состав и суммы зафиксированы, золото ещё не списано', paid: 'Золото списано из казны, начисления закрыты', cancelled: 'Выплата отменена, начисления освобождены' }
const players = computed(() => (payout.value?.players ?? []).filter(player => player.nickname_snapshot.toLowerCase().includes(search.value.toLowerCase())&&(!statusFilter.value||player.status===statusFilter.value)))
const pendingVisible = computed(() => players.value.filter(row=>row.status==='pending'))
async function load() { loading.value=true;error.value='';try{payout.value=(await api.get(`/api/payouts/${route.params.id}`)).data}catch(e){error.value=e.response?.status===403?'У вас нет доступа к этой выплате.':'Не удалось загрузить выплату.'}finally{loading.value=false} }
async function action(name) { if(!confirm(name==='complete'?'Подтвердить фактическую выплату золота всем участникам?':name==='cancel'?'Отменить эту выплату?':'Рассчитать выплату?'))return;busy.value=true;error.value='';try{await api.post(`/api/payouts/${payout.value.id}/${name}`);await load()}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Операция не выполнена.'}finally{busy.value=false} }
async function removeDraft() { if(!confirm('Удалить этот черновик нахрюка?'))return;busy.value=true;error.value='';try{await api.delete(`/api/payouts/${payout.value.id}`);await router.push('/payouts')}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Не удалось удалить черновик.'}finally{busy.value=false} }
function toggleAll(){selected.value=selected.value.length===pendingVisible.value.length?[]:pendingVisible.value.map(row=>row.player_id)}
async function paySelected(){if(!selected.value.length||!confirm(`Подтвердить фактическую выдачу ${selected.value.length} игрокам?`))return;busy.value=true;error.value='';try{await api.post(`/api/payouts/${payout.value.id}/pay-players`,{player_ids:selected.value});selected.value=[];await load()}catch(e){error.value=Object.values(e.response?.data?.errors??{}).flat()[0]??e.response?.data?.message??'Выдача не отмечена.'}finally{busy.value=false}}
async function download(format){exporting.value=format;try{const response=await api.get(`/api/payouts/${payout.value.id}/export`,{params:{format,search:search.value||undefined,status:statusFilter.value||undefined},responseType:'blob'});const url=URL.createObjectURL(response.data);const a=document.createElement('a');a.href=url;a.download=`payout-${payout.value.id}.${format}`;a.click();URL.revokeObjectURL(url)}finally{exporting.value=''}}
function date(value,withTime=false){if(!value)return'—';return new Date(value).toLocaleString('ru-RU',withTime?{}:{dateStyle:'short'})}
function tokens(value){return Number(payout.value?.token_unit_value)>0?Math.floor(Number(value)/Number(payout.value.token_unit_value)):0}
onMounted(load)
</script>

<template><section>
  <div v-if="loading" class="panel empty">Загрузка выплаты…</div>
  <template v-else-if="payout">
    <div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · НАХРЮК</p><h1>Нахрюк #{{ payout.id }}</h1><p class="muted">{{ date(payout.period_from) }} — {{ date(payout.period_to) }}</p></div><div v-if="auth.canManage" class="page-actions"><button v-if="payout.status==='draft'" class="primary" :disabled="busy" @click="action('calculate')">Продолжить и рассчитать</button><button v-if="payout.status==='draft'" class="danger" :disabled="busy" @click="removeDraft">Удалить черновик</button><button v-if="payout.status==='calculated'&&auth.canCreatePayouts" class="primary" :disabled="busy" @click="action('complete')">Выдать всем ожидающим</button><button v-if="payout.status==='calculated'" class="secondary" :disabled="busy" @click="action('cancel')">Отменить</button></div></div>
    <p v-if="error" class="notice error">{{ error }}</p>
    <div class="payout-summary-grid"><div class="panel"><span>Статус</span><strong :class="['import-status',payout.status==='paid'?'confirmed':'draft']" :title="statusDescriptions[payout.status]">{{ statusLabels[payout.status] }}</strong></div><div class="panel"><span>Общая сумма / жетоны</span><strong><GoldAmount :value="Number(payout.total_amount).toLocaleString('ru-RU')"/> <span class="stat-divider">/</span> <TokenAmount :value="tokens(payout.total_amount).toLocaleString('ru-RU')"/></strong></div><div class="panel"><span>Участников</span><strong>{{ payout.players.length }}</strong></div><div class="panel"><span>Создал</span><strong>{{ payout.creator?.discord_display_name || payout.creator?.discord_username || 'Система' }}</strong></div><div class="panel"><span>Рассчитан</span><strong>{{ date(payout.calculated_at,true) }}</strong></div><div class="panel"><span>Выплачен</span><strong>{{ date(payout.paid_at,true) }}</strong></div></div>
    <div class="panel payout-player-panel"><div class="panel-title payout-detail-toolbar"><div><h2>Платёжная ведомость</h2><p class="muted">Фильтры применяются и к экспорту</p></div><input v-model.trim="search" placeholder="Поиск по никнейму"><select v-model="statusFilter"><option value="">Все статусы</option><option value="pending">Ожидает</option><option value="paid">Выплачено</option><option value="cancelled">Отменено</option></select><button :disabled="exporting" @click="download('csv')">CSV</button><button :disabled="exporting" @click="download('xlsx')">XLSX</button></div><div v-if="payout.status==='calculated'&&auth.canCreatePayouts" class="payout-bulk-bar"><button @click="toggleAll">{{ selected.length===pendingVisible.length&&selected.length?'Снять выбор':'Выбрать ожидающих' }}</button><span>Выбрано: {{ selected.length }}</span><button class="primary" :disabled="busy||!selected.length" @click="paySelected">Отметить фактически выданными</button></div><div class="table-wrap flat"><table><thead><tr><th v-if="payout.status==='calculated'&&auth.canCreatePayouts"></th><th>Никнейм</th><th>Посещение праймов</th><th>Праймы</th><th>Статус</th><th class="right">Сумма</th></tr></thead><tbody><tr v-for="player in players" :key="player.id"><td v-if="payout.status==='calculated'&&auth.canCreatePayouts"><input v-if="player.status==='pending'" v-model="selected" type="checkbox" :value="player.player_id"></td><td><strong>{{ player.nickname_snapshot }}</strong></td><td>{{ Number(player.prime_attendance_percentage_snapshot).toLocaleString('ru-RU') }}%</td><td>{{ player.primes_count }}</td><td><span :class="['import-status',player.status==='paid'?'confirmed':'draft']">{{ {pending:'Ожидает',paid:'Выплачено',cancelled:'Отменено'}[player.status] }}</span></td><td class="right transaction-amount"><GoldAmount :value="Number(player.amount).toLocaleString('ru-RU')"/></td></tr><tr v-if="!players.length"><td colspan="6" class="empty">Участники не найдены.</td></tr></tbody></table></div></div>
    <div class="panel payout-activity-panel"><div class="panel-title"><h2>Включённые праймы</h2><span class="muted">{{ payout.activities.length }}</span></div><div v-if="payout.activities.length" class="payout-activity-list"><RouterLink v-for="activity in payout.activities" :key="activity.id" :to="`/activities/${activity.id}`"><div><strong>{{ activity.definition?.name }}</strong><small>{{ date(activity.occurred_at,true) }}</small></div><span>Прайм</span><b><GoldAmount :value="Number(activity.gold_value).toLocaleString('ru-RU')"/></b></RouterLink></div><p v-else class="empty">Праймы появятся после расчёта.</p></div>
    <p v-if="['paid','cancelled'].includes(payout.status)" class="notice">Завершённая выплата защищена от изменений.</p>
  </template>
  <div v-else class="panel"><p class="notice error">{{ error }}</p><RouterLink class="secondary" to="/payouts">Вернуться к выплатам</RouterLink></div>
</section></template>
