<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../api.js'
import StatCard from '../components/StatCard.vue'
import GoldAmount from '../components/GoldAmount.vue'
import { useAuthStore } from '../stores/auth.js'
import { apiErrorMessage, useNotificationsStore } from '../stores/notifications.js'

const auth = useAuthStore()
const notifications = useNotificationsStore()
const data = ref({ gold: 0, inventory_value: 0, items: [], recent_drops: [], transactions: [], gold_transactions: [] })
const issueOptions = ref({ players: [], activities: [] })
const error = ref('')
const saleItem = ref(null); const saleQuantity = ref(1); const saleAmount = ref(0); const saleComment = ref('')
const issueItem = ref(null); const issueQuantity = ref(1); const recipientId = ref(''); const sourceActivityId = ref(''); const issueReason = ref('')
const busy = ref(false)
const goldOperation = ref(null); const goldAmount = ref(1); const goldDescription = ref('')
const transactionLabels = { loot_income: 'Поступление лута', issue: 'Выдача игроку', auction_reserve: 'Резерв аукциона', auction_release: 'Снятие резерва', auction_sale: 'Продажа на аукционе', manual_sale: 'Ручная продажа', adjustment: 'Корректировка' }
const goldTransactionLabels = { auction_income: 'Продажа на аукционе', payout: 'Выплата нахрюка', manual_income: 'Продажа вне гильдии / пополнение', manual_expense: 'Ручной расход', adjustment: 'Корректировка' }

async function load() { try { data.value = (await api.get('/api/treasury')).data } catch (requestError) { error.value = requestError.response?.data?.message ?? 'Не удалось загрузить казну.' } }
function availableItems() { return data.value.items.filter(item => item.available_quantity > 0) }
function openSale(item = availableItems()[0]) { if (!auth.canManage || !item) return; saleItem.value = item; saleQuantity.value = 1; saleAmount.value = Number(item.unit_value); saleComment.value = 'Продажа предмета вне аукциона'; error.value = '' }
function updateAmount() { if (saleItem.value) saleAmount.value = Number(saleItem.value.unit_value) * Number(saleQuantity.value) }
async function sell() { busy.value = true; error.value = ''; try { await api.post(`/api/treasury/items/${saleItem.value.id}/sell`, { quantity: saleQuantity.value, total_amount: saleAmount.value, comment: saleComment.value }); saleItem.value = null; await load(); notifications.success('Продажа проведена, золото зачислено в казну.') } catch (requestError) { error.value = apiErrorMessage(requestError, 'Не удалось провести продажу.'); notifications.error(error.value) } finally { busy.value = false } }
function openGoldOperation(operation) { if (!auth.canManage) return; goldOperation.value = operation; goldAmount.value = 1; goldDescription.value = ''; error.value = '' }
async function saveGoldOperation() { busy.value = true; error.value = ''; const operation = goldOperation.value; try { await api.post('/api/treasury/transactions', { operation, amount: goldAmount.value, description: goldDescription.value }); goldOperation.value = null; await load(); notifications.success(operation === 'income' ? 'Золото добавлено в казну.' : 'Золото списано из казны.') } catch (requestError) { error.value = apiErrorMessage(requestError, 'Не удалось провести операцию.'); notifications.error(error.value) } finally { busy.value = false } }

async function openIssue(item = availableItems()[0]) {
  if (!auth.canManage || !item) return
  issueItem.value = item; issueQuantity.value = 1; recipientId.value = ''; sourceActivityId.value = ''; issueReason.value = ''; error.value = ''
  if (!issueOptions.value.players.length) {
    try { issueOptions.value = (await api.get('/api/treasury/issue-options')).data }
    catch (requestError) { error.value = requestError.response?.data?.message ?? 'Не удалось загрузить список получателей.' }
  }
}
async function issue() {
  busy.value = true; error.value = ''
  try {
    await api.post(`/api/treasury/items/${issueItem.value.id}/issue`, { quantity: issueQuantity.value, recipient_player_id: Number(recipientId.value), source_activity_id: sourceActivityId.value ? Number(sourceActivityId.value) : null, reason: issueReason.value })
    issueItem.value = null; await load(); notifications.success('Предмет выдан игроку.')
  } catch (requestError) { error.value = apiErrorMessage(requestError, 'Не удалось выдать предмет.'); notifications.error(error.value) }
  finally { busy.value = false }
}
function activityLabel(activity) { return `${activity.definition?.name ?? 'Событие'} · ${new Date(activity.occurred_at).toLocaleDateString('ru-RU')}` }
onMounted(load)
</script>

<template><section>
  <div class="page-heading"><div><p class="eyebrow">ЭКОНОМИКА · КАЗНА</p><h1>Казна гильдии</h1></div><div v-if="auth.canManage" class="page-actions"><button class="danger" @click="openGoldOperation('expense')">Списать золото</button></div></div>
  <div class="stats-row"><StatCard label="Золото в казне" :value="Number(data.gold).toLocaleString('ru-RU')" gold note="Фактический золотой баланс" accent/><StatCard label="Дроп с РБ (экв. золота)" :value="Number(data.inventory_value).toLocaleString('ru-RU')" gold note="Количество × указанная стоимость"/></div>
  <p v-if="error&&!saleItem&&!issueItem" class="notice error">{{ error }}</p>
  <div class="treasury-workspace"><div class="treasury-side"><div class="panel inventory-panel"><div class="panel-title"><h2>Инвентарь</h2><span class="muted">{{ data.items.length }} позиций · {{ data.items.reduce((sum,item)=>sum+Number(item.quantity),0) }} предметов</span></div><div v-if="data.items.length" class="inventory-grid"><article v-for="item in data.items" :key="item.id" class="inventory-slot" :title="`${item.item_name}\n${item.quantity} шт. · ${Number(item.unit_value).toLocaleString('ru-RU')} золота за единицу`"><img v-if="item.icon_url" :src="item.icon_url" :alt="item.item_name"><span v-else class="slot-placeholder">{{ item.item_name.slice(0,1).toUpperCase() }}</span><b>{{ item.quantity }}</b><div class="slot-info"><strong>{{ item.item_name }}</strong><small><GoldAmount :value="Number(item.unit_value).toLocaleString('ru-RU')"/> / шт.</small><span v-if="item.reserved_quantity">В резерве: {{ item.reserved_quantity }}</span><div v-if="auth.canManage&&item.available_quantity>0" class="slot-actions"><button type="button" @click.stop="openIssue(item)">Выдать</button><button type="button" @click.stop="openSale(item)">Продать</button></div></div></article></div><p v-else class="empty">Инвентарь пока пуст.</p></div>
    <div class="panel recent-drop"><div class="panel-title"><h2>Последний дроп</h2><span class="muted">По активностям</span></div><div v-if="data.recent_drops.length" class="activity-drop-list"><RouterLink v-for="drop in data.recent_drops" :key="drop.id" :to="`/activities/${drop.id}`" :style="drop.icon_url?{backgroundImage:`linear-gradient(90deg,rgba(9,7,4,.72),rgba(9,7,4,.96) 68%),url(${drop.icon_url})`}:{}"><div class="activity-drop-main"><span class="activity-drop-source">Активность</span><strong>{{ drop.name }}</strong><small>{{ drop.type === 'mini_activity' ? 'Мини-прайм' : 'Прайм' }} · {{ new Date(drop.occurred_at).toLocaleDateString('ru-RU') }}</small><div class="activity-drop-items"><span v-for="item in drop.items" :key="item.id" :title="item.name"><img v-if="item.icon_url" :src="item.icon_url" :alt="item.name"><i v-else>?</i><b>{{ item.quantity }}</b></span></div></div><GoldAmount :value="Number(drop.total_value).toLocaleString('ru-RU')"/></RouterLink></div><p v-else class="empty">Дропа из активностей пока нет.</p></div></div>
    <div class="treasury-histories"><div class="panel history-panel"><div class="panel-title"><h2>История движения предметов</h2><span class="muted">Последние 50 операций</span></div><div v-if="data.transactions.length" class="table-wrap flat"><table><thead><tr><th>Дата</th><th>Предмет</th><th>Операция</th><th>Получатель</th><th>Провёл</th><th class="right">Кол-во</th></tr></thead><tbody><tr v-for="tx in data.transactions" :key="tx.id"><td class="muted">{{ new Date(tx.created_at).toLocaleString('ru-RU') }}</td><td><span class="history-entity"><img v-if="tx.item?.icon_url" :src="tx.item.icon_url" :alt="tx.item.item_name"><i v-else>?</i><strong>{{ tx.item?.item_name }}</strong></span></td><td><strong>{{ transactionLabels[tx.type] ?? tx.type }}</strong><small class="history-note">{{ tx.reason }}<template v-if="tx.source_activity"> · {{ tx.source_activity.definition?.name }}</template></small></td><td>{{ tx.recipient?.nickname ?? '—' }}</td><td>{{ tx.creator?.discord_display_name || tx.creator?.discord_username || 'Система' }}</td><td class="right transaction-amount" :class="{negative:tx.quantity_delta<0}">{{ tx.quantity_delta>0?'+':'' }}{{ tx.quantity_delta }}</td></tr></tbody></table></div><div v-else class="empty-state">Транзакции казны пока отсутствуют.</div></div>
    <div class="panel history-panel"><div class="panel-title"><h2>История золота</h2><span class="muted">Последние 50 операций</span></div><div v-if="data.gold_transactions.length" class="table-wrap flat"><table><thead><tr><th>Дата</th><th>Операция</th><th>Описание</th><th>Провёл</th><th class="right">Сумма</th><th class="right">Баланс</th></tr></thead><tbody><tr v-for="tx in data.gold_transactions" :key="tx.id"><td class="muted">{{ new Date(tx.created_at).toLocaleString('ru-RU') }}</td><td><span class="history-entity gold"><img src="/images/gold.png" alt="Золото"><strong>{{ goldTransactionLabels[tx.type] ?? tx.type }}</strong></span></td><td>{{ tx.description }}</td><td>{{ tx.creator?.discord_display_name || tx.creator?.discord_username || 'Система' }}</td><td class="right transaction-amount" :class="{negative:Number(tx.amount)<0}"><GoldAmount :value="`${Number(tx.amount)>0?'+':''}${Number(tx.amount).toLocaleString('ru-RU')}`"/></td><td class="right"><GoldAmount :value="Number(tx.balance_after).toLocaleString('ru-RU')"/></td></tr></tbody></table></div><div v-else class="empty-state">Операций с золотом пока нет.</div></div></div></div>

  <div v-if="saleItem" class="modal" @click.self="saleItem=null"><form class="form-card" @submit.prevent="sell"><h2>Продать предмет</h2><label>Предмет<select v-model="saleItem" required @change="saleQuantity=1;updateAmount()"><option v-for="item in availableItems()" :key="item.id" :value="item">{{ item.item_name }} · доступно {{ item.available_quantity }}</option></select></label><label>Количество<input v-model.number="saleQuantity" type="number" min="1" :max="saleItem.available_quantity" required @input="updateAmount"></label><label>Фактическая сумма продажи, золото<input v-model.number="saleAmount" type="number" min="1" step="1" required></label><label>Комментарий<textarea v-model.trim="saleComment" maxlength="500" required></textarea></label><p class="muted">Будет списано {{ saleQuantity }} шт. и зачислено {{ Number(saleAmount).toLocaleString('ru-RU') }} золота.</p><p v-if="error" class="notice error">{{ error }}</p><div class="form-actions"><button type="button" @click="saleItem=null">Отмена</button><button class="primary" :disabled="busy">Подтвердить продажу</button></div></form></div>
  <div v-if="issueItem" class="modal" @click.self="issueItem=null"><form class="form-card" @submit.prevent="issue"><h2>Выдать предмет</h2><label>Предмет<select v-model="issueItem" required @change="issueQuantity=1"><option v-for="item in availableItems()" :key="item.id" :value="item">{{ item.item_name }} · доступно {{ item.available_quantity }}</option></select></label><label>Количество<input v-model.number="issueQuantity" type="number" min="1" :max="issueItem.available_quantity" required></label><label>Получатель<select v-model="recipientId" required><option value="" disabled>Выберите игрока</option><option v-for="player in issueOptions.players" :key="player.id" :value="player.id">{{ player.nickname }}</option></select></label><label>Исходная активность<select v-model="sourceActivityId"><option value="">Без привязки к активности</option><option v-for="activity in issueOptions.activities" :key="activity.id" :value="activity.id">{{ activityLabel(activity) }}</option></select></label><label>Причина / комментарий<textarea v-model.trim="issueReason" maxlength="500" required placeholder="За что выдан предмет"></textarea></label><p class="muted">Операция сохранится в истории и уменьшит остаток на {{ issueQuantity }} шт.</p><p v-if="error" class="notice error">{{ error }}</p><div class="form-actions"><button type="button" @click="issueItem=null">Отмена</button><button class="primary" :disabled="busy||!recipientId">Подтвердить выдачу</button></div></form></div>
  <div v-if="goldOperation" class="modal" @click.self="goldOperation=null"><form class="form-card" @submit.prevent="saveGoldOperation"><h2>{{ goldOperation==='income'?'Добавить золото':'Списать золото' }}</h2><label>Сумма, золото<input v-model.number="goldAmount" type="number" min="1" step="1" required></label><label>Основание операции<textarea v-model.trim="goldDescription" maxlength="500" required placeholder="Например: взнос участника или покупка расходников"></textarea></label><p class="muted">Текущий баланс: <GoldAmount :value="Number(data.gold).toLocaleString('ru-RU')"/>. Операция сохранится в финансовой истории.</p><p v-if="error" class="notice error">{{ error }}</p><div class="form-actions"><button type="button" @click="goldOperation=null">Отмена</button><button class="primary" :disabled="busy">{{ busy?'Сохранение…':'Подтвердить' }}</button></div></form></div>
</section></template>
