<?php
namespace App\Actions;
use App\Jobs\SendDiscordNotification;use App\Models\Auction;use App\Models\AuctionBid;use App\Models\TreasuryItem;use App\Models\TreasuryItemTransaction;use App\Models\TreasuryTransaction;use App\Services\ArmoryNotificationService;use App\Services\AuditService;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
final class FinishAuction
{
 public function __construct(private readonly AuditService $audit,private readonly ArmoryNotificationService $notifications){}
 public function execute(Auction $auction,int $userId):Auction
 {
  return DB::transaction(function()use($auction,$userId){$locked=Auction::query()->lockForUpdate()->findOrFail($auction->id);if($locked->status!=='active')throw ValidationException::withMessages(['auction'=>__('domain.auction.finish_active_only')]);if($locked->ends_at->isFuture())throw ValidationException::withMessages(['auction'=>__('domain.auction.not_finished_yet')]);$item=TreasuryItem::query()->lockForUpdate()->findOrFail($locked->treasury_item_id);$winner=AuctionBid::query()->with('player:id,nickname')->where('auction_id',$locked->id)->orderByDesc('amount')->orderBy('created_at')->orderBy('id')->lockForUpdate()->first();if(!$winner){$item->decrement('reserved_quantity',$locked->quantity);$locked->update(['status'=>'finished','finished_at'=>now()]);$this->audit->record('auction.finished_without_bids',$locked,['status'=>'active'],['status'=>'finished']);DB::afterCommit(fn()=>$this->notifyFinished($locked,$item,null));return $locked->refresh()->load(['item','winner']);}$tokenUnitValue=(int)$locked->token_unit_value_snapshot;if($tokenUnitValue<=0)throw ValidationException::withMessages(['auction'=>__('domain.auction.token_value_snapshot_missing')]);$goldAmount=(int)$winner->amount*$tokenUnitValue;$item->quantity-=$locked->quantity;$item->reserved_quantity-=$locked->quantity;$item->save();TreasuryItemTransaction::query()->create(['treasury_item_id'=>$item->id,'type'=>'auction_sale','quantity_delta'=>-$locked->quantity,'auction_id'=>$locked->id,'reason'=>'Продажа на аукционе #'.$locked->id,'created_by'=>$userId]);DB::select('SELECT pg_advisory_xact_lock(?)',[834721]);$previous=(int)(TreasuryTransaction::query()->latest('id')->value('balance_after')??0);TreasuryTransaction::query()->create(['type'=>'auction_income','amount'=>$goldAmount,'balance_after'=>$previous+$goldAmount,'description'=>'Продажа '.$item->item_name.' на аукционе #'.$locked->id.' за '.$winner->amount.' жетонов','related_entity_type'=>Auction::class,'related_entity_id'=>$locked->id,'created_by'=>$userId]);$locked->update(['status'=>'finished','winner_player_id'=>$winner->player_id,'winning_bid'=>$winner->amount,'finished_at'=>now()]);$this->audit->record('auction.finished',$locked,['status'=>'active'],['status'=>'finished','winner_player_id'=>$winner->player_id,'winning_bid'=>$winner->amount,'gold_income'=>$goldAmount]);DB::afterCommit(fn()=>$this->notifyFinished($locked,$item,$winner));return $locked->refresh()->load(['item','winner']);});
 }
 private function notifyFinished(Auction $auction,TreasuryItem $item,?AuctionBid $winner):void{$message=$winner?'«'.$item->item_name.'» выиграл **'.$winner->player->nickname.'** за **'.number_format($winner->amount,0,'',' ').' жетонов**.':'На лот «'.$item->item_name.'» не было ставок.';SendDiscordNotification::dispatch('Аукцион завершён',$message,$winner?'green':'red','auctions');$this->notifications->notify($this->notifications->activeMembers(),'auction_finished','Аукцион завершён',strip_tags(str_replace('**','',$message)),'/auctions/'.$auction->id,'auction-finished-'.$auction->id);}
}
