<?php
namespace App\Http\Controllers;
use App\Actions\CalculatePayout;
use App\Actions\CompletePayout;
use App\Actions\PayPayoutPlayers;
use App\Models\Activity;
use App\Models\Payout;
use App\Models\PrimePlayerEarning;
use App\Services\AuditService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Carbon\CarbonImmutable;
final class PayoutController extends Controller
{
    public function index(Request $request){$q=Payout::query()->with(['players','activities.definition:id,name,type'])->orderByDesc('id');if(!$request->user()->canCreatePayouts()){abort_unless($request->user()->player,403);$q->whereHas('players',fn($p)=>$p->where('player_id',$request->user()->player->id));}return $q->get();}
    public function show(Request $request,Payout $payout){if(!$request->user()->canCreatePayouts()){abort_unless($request->user()->player&&$payout->players()->where('player_id',$request->user()->player->id)->exists(),403);}$result=$payout->load(['creator:id,discord_username,discord_display_name','players'=>fn($q)=>$q->orderByDesc('amount')->orderBy('nickname_snapshot'),'activities'=>fn($q)=>$q->whereHas('definition',fn($definition)=>$definition->where('type','prime'))->with('definition:id,name,type')->orderByDesc('occurred_at')]);$result->setAttribute('token_unit_value',(int)(DB::table('treasury_token_settings')->where('id',1)->value('token_unit_value')??0));return $result;}
    public function store(Request $request,AuditService $audit,CalculatePayout $calculate){abort_unless($request->user()->canCreatePayouts(),403);$data=$request->validate(['period_from'=>['nullable','required_without:activity_ids','date'],'period_to'=>['nullable','required_without:activity_ids','date','after_or_equal:period_from'],'activity_ids'=>['nullable','array','min:1'],'activity_ids.*'=>['integer','distinct','exists:activities,id']]);$activityIds=$data['activity_ids']??null;if($activityIds){$dates=Activity::query()->whereIn('id',$activityIds)->selectRaw('MIN(occurred_at) AS first, MAX(occurred_at) AS last')->first();$data['period_from']=CarbonImmutable::parse($dates->first)->toDateString();$data['period_to']=CarbonImmutable::parse($dates->last)->toDateString();}unset($data['activity_ids']);return DB::transaction(function()use($request,$data,$activityIds,$audit,$calculate){$payout=Payout::query()->create($data+['status'=>'draft','created_by'=>$request->user()->id]);$audit->record('payout.created',$payout,null,$payout->getAttributes()+['activity_ids'=>$activityIds]);$calculated=$calculate->execute($payout,$activityIds);return response()->json($calculated,201);});}
    public function calculate(Request $request,Payout $payout,CalculatePayout $action){abort_unless($request->user()->canCreatePayouts(),403);return $action->execute($payout);}
    public function complete(Request $request,Payout $payout,CompletePayout $action){abort_unless($request->user()->canCreatePayouts(),403);return $action->execute($payout,$request->user()->id);}
    public function payPlayers(Request $request,Payout $payout,PayPayoutPlayers $action){abort_unless($request->user()->canCreatePayouts(),403);$ids=$request->validate(['player_ids'=>['required','array','min:1'],'player_ids.*'=>['integer','distinct','exists:players,id']])['player_ids'];return $action->execute($payout,$ids,$request->user()->id);}
    public function cancel(Request $request,Payout $payout,AuditService $audit){abort_unless($request->user()->canCreatePayouts(),403);return DB::transaction(function()use($payout,$audit){$locked=Payout::query()->lockForUpdate()->findOrFail($payout->id);if(!in_array($locked->status,['draft','calculated'],true))throw ValidationException::withMessages(['payout'=>'Этот нахрюк нельзя отменить.']);if($locked->players()->where('status','paid')->exists())throw ValidationException::withMessages(['payout'=>'Частично выданный нахрюк отменить нельзя.']);PrimePlayerEarning::query()->where('payout_id',$locked->id)->where('status','pending')->update(['payout_id'=>null]);$locked->activities()->detach();$locked->players()->where('status','pending')->update(['status'=>'cancelled']);$old=$locked->status;$locked->update(['status'=>'cancelled']);$audit->record('payout.cancelled',$locked,['status'=>$old],['status'=>'cancelled']);return $locked->refresh()->load('players');});}
    public function destroy(Request $request,Payout $payout,AuditService $audit){abort_unless($request->user()->canCreatePayouts(),403);return DB::transaction(function()use($payout,$audit){$locked=Payout::query()->lockForUpdate()->findOrFail($payout->id);if($locked->status!=='draft')throw ValidationException::withMessages(['payout'=>'Удалить можно только черновик.']);if($locked->players()->exists()||$locked->activities()->exists())throw ValidationException::withMessages(['payout'=>'Черновик уже содержит рассчитанные данные и не может быть удалён.']);$old=$locked->getAttributes();$audit->record('payout.deleted',$locked,$old,null);$locked->delete();return response()->noContent();});}
}
